begin;

-- Generado por lib/migraciones/generar_0025.py desde BASE_ACTUALIZADA_NV_ka.xlsx — no editar a mano.
-- Uno de varios archivos partidos (ver README.md) — correr TODOS, en cualquier orden, cada uno es su propia transacción.

-- Parte 10 de 10.

-- Categoría comodín para negocios sin categoría reconocible en el
-- Excel (columna NOT NULL, no se puede dejar en blanco). activo=false
-- así no aparece como chip de filtro en el buscador público.
insert into categorias_oficiales (nombre, slug, descripcion, icono, orden, activo)
select 'Pendiente de clasificar', 'pendiente-clasificar',
  'Negocio importado de la base CDMB sin categoría oficial asignada todavía — revisar y corregir desde /admin/negocios.',
  '⏳', 99, false
where not exists (select 1 from categorias_oficiales where slug = 'pendiente-clasificar');

delete from negocios where nombre = 'Bucarretes SAS BIC';

-- Veredas encontradas en la base real (normalizadas de escritura).
insert into veredas (municipio, nombre, slug) values
  ('Bucaramanga', 'Perimetro Urbano', 'perimetro-urbano'),
  ('Bucaramanga', 'Rosa Blanca', 'rosa-blanca'),
  ('Bucaramanga', 'San Jose', 'san-jose'),
  ('Bucaramanga', 'San Pedro Bajo', 'san-pedro-bajo'),
  ('Bucaramanga', 'Santos Bajo', 'santos-bajo'),
  ('Bucaramanga', 'Vijagual', 'vijagual'),
  ('California', 'Centro', 'centro'),
  ('California', 'Perimetro Urbano', 'perimetro-urbano'),
  ('Charta', 'Centro Trincheras Parte Baja', 'centro-trincheras-parte-baja'),
  ('Charta', 'El Roble', 'el-roble'),
  ('Charta', 'Perimetro Urbano', 'perimetro-urbano'),
  ('El Playón', 'Perimetro Urbano', 'perimetro-urbano'),
  ('El Playón', 'San Pedro de la Tigra', 'san-pedro-de-la-tigra'),
  ('Floridablanca', 'Helechales', 'helechales'),
  ('Floridablanca', 'LA Judia', 'la-judia'),
  ('Floridablanca', 'Monterrey - Acapulco', 'monterrey-acapulco'),
  ('Floridablanca', 'Perimetro Urbano', 'perimetro-urbano'),
  ('Floridablanca', 'Vericute', 'vericute'),
  ('Girón', 'Acapulco', 'acapulco'),
  ('Girón', 'Altamira', 'altamira'),
  ('Girón', 'Chocoita', 'chocoita'),
  ('Girón', 'El Cedro', 'el-cedro'),
  ('Girón', 'Lagunetas', 'lagunetas'),
  ('Girón', 'Llano Grande', 'llano-grande'),
  ('Girón', 'Motoso', 'motoso'),
  ('Girón', 'Nazareth', 'nazareth'),
  ('Girón', 'Palmitas', 'palmitas'),
  ('Girón', 'Perimetro Urbano', 'perimetro-urbano'),
  ('Girón', 'Rio Frio', 'rio-frio'),
  ('Lebrija', 'Altos de Palonegro', 'altos-de-palonegro'),
  ('Lebrija', 'Cuchilla', 'cuchilla'),
  ('Lebrija', 'EL Cosme', 'el-cosme'),
  ('Lebrija', 'La Cuchilla', 'la-cuchilla'),
  ('Lebrija', 'Lisboa', 'lisboa'),
  ('Lebrija', 'Palonegro', 'palonegro'),
  ('Lebrija', 'Panorama', 'panorama'),
  ('Lebrija', 'Perimetro Urbano', 'perimetro-urbano'),
  ('Lebrija', 'Piedras Negras', 'piedras-negras'),
  ('Lebrija', 'San Gabriel', 'san-gabriel'),
  ('Lebrija', 'San Nicolas', 'san-nicolas'),
  ('Lebrija', 'San Nicolas Alto', 'san-nicolas-alto'),
  ('Lebrija', 'San Nicolas Bajo', 'san-nicolas-bajo'),
  ('Lebrija', 'Santa Rosa', 'santa-rosa'),
  ('Lebrija', 'Santo Domingo', 'santo-domingo'),
  ('Matanza', 'Alto Bravo', 'alto-bravo'),
  ('Matanza', 'Aventinos', 'aventinos'),
  ('Matanza', 'El Filo', 'el-filo'),
  ('Matanza', 'Santa Ana', 'santa-ana'),
  ('Piedecuesta', 'Barrio Blanco', 'barrio-blanco'),
  ('Piedecuesta', 'Blanquiscal', 'blanquiscal'),
  ('Piedecuesta', 'Caneyes', 'caneyes'),
  ('Piedecuesta', 'Casiano', 'casiano'),
  ('Piedecuesta', 'Cristales', 'cristales'),
  ('Piedecuesta', 'Diamante', 'diamante'),
  ('Piedecuesta', 'El Diamante', 'el-diamante'),
  ('Piedecuesta', 'El Duende', 'el-duende'),
  ('Piedecuesta', 'El Guamo', 'el-guamo'),
  ('Piedecuesta', 'El Volador', 'el-volador'),
  ('Piedecuesta', 'Guatiguara', 'guatiguara'),
  ('Piedecuesta', 'La Colombiana', 'la-colombiana'),
  ('Piedecuesta', 'La Esperanza', 'la-esperanza'),
  ('Piedecuesta', 'La Urgua', 'la-urgua'),
  ('Piedecuesta', 'Los Colorados', 'los-colorados'),
  ('Piedecuesta', 'Mesita de San Javier', 'mesita-de-san-javier'),
  ('Piedecuesta', 'Monterredondo', 'monterredondo'),
  ('Piedecuesta', 'Perimetro Urbano', 'perimetro-urbano'),
  ('Piedecuesta', 'San Francisco', 'san-francisco'),
  ('Piedecuesta', 'San Miguel', 'san-miguel'),
  ('Piedecuesta', 'Sevilla', 'sevilla'),
  ('Piedecuesta', 'Umpala', 'umpala'),
  ('Piedecuesta', 'Via Curos', 'via-curos'),
  ('Piedecuesta', 'Volador', 'volador'),
  ('Rionegro', 'Honduras Caña Brava', 'honduras-cana-brava'),
  ('Rionegro', 'La Ceiba', 'la-ceiba'),
  ('Rionegro', 'La Cristalina', 'la-cristalina'),
  ('Rionegro', 'La Paz', 'la-paz'),
  ('Rionegro', 'La Plazueña', 'la-plazuena'),
  ('Rionegro', 'La Union', 'la-union'),
  ('Rionegro', 'La Union de Galapagos de Rionegro', 'la-union-de-galapagos-de-rionegro'),
  ('Rionegro', 'Perimetro Urbano', 'perimetro-urbano'),
  ('Rionegro', 'Popas', 'popas'),
  ('Rionegro', 'Portachuelo', 'portachuelo'),
  ('Rionegro', 'San Jose Arevalo', 'san-jose-arevalo'),
  ('Rionegro', 'San Pablo', 'san-pablo'),
  ('Rionegro', 'Valparaiso', 'valparaiso'),
  ('Suratá', 'Bachiga', 'bachiga'),
  ('Suratá', 'Capilla Alta', 'capilla-alta'),
  ('Suratá', 'El Porvenir', 'el-porvenir'),
  ('Suratá', 'La Violeta', 'la-violeta'),
  ('Suratá', 'Vereda Porvenir', 'vereda-porvenir'),
  ('Tona', 'Berlin', 'berlin'),
  ('Tona', 'Perimetro Urbano', 'perimetro-urbano'),
  ('Tona', 'Pirgua Parte Baje', 'pirgua-parte-baje'),
  ('Tona', 'Vegas', 'vegas'),
  ('Vetas', 'El Salado', 'el-salado'),
  ('Vetas', 'LA Chorrera', 'la-chorrera'),
  ('Vetas', 'Mongora', 'mongora')
on conflict (municipio, slug) do nothing;


-- Negocios de esta parte (INSERT + categoría/subcategoría/actividad + puntajes de cada uno, juntos).

-- PARQUE LAS HELICONIAS
insert into negocios (id, nombre, slug, categoria_oficial_id, municipio, vereda_id, direccion, latitud, longitud, descripcion_corta, descripcion, producto, telefono, whatsapp, email, representante_legal, nit, naturaleza_juridica, delegado, tiempo_constitucion, rut_camara_comercio, responsable_cdmb, novedad, tipo_negocio_verde, codigo_marca, anio_registro, cota_msnm, este, norte, aplicacion_ficha_2025, observaciones, registro_nacional_turismo, uso_suelo, concesion_aguas, concesion_aguas_vencimiento, vertimientos, vertimientos_vencimiento, pueaa, pgris, pozo_septico, alcantarillado, ica, ica_vencimiento, invima, invima_vencimiento, certificado_tenencia_animales, buenas_practicas_agricolas, buenas_practicas_apicolas, registro_apicola, intervencion_cauce, capacidad_carga, sstt, canal_venta, exportacion, huella_carbono, fortalecimiento_tecnico, fortalecimiento_academico, fortalecimiento_financiero, internacionalizacion, certificaciones, posicionamiento_marca, beneficios_ventanilla, fortalezas_ambiental, fortalezas_social, fortalezas_economico, debilidades_ambiental, debilidades_social, debilidades_financiera, emprendimiento_verde, sello_marca, avalado, destacado, activo) values ('672b5be6-3791-4acb-9506-d248bb745708', 'PARQUE LAS HELICONIAS', generar_slug_unico('PARQUE LAS HELICONIAS', '672b5be6-3791-4acb-9506-d248bb745708'), (select id from categorias_oficiales where slug = 'bioproductos-servicios-sostenibles'), 'Rionegro', (select id from veredas where municipio = 'Rionegro' and slug = 'la-cristalina'), 'VEREDA LA CRISTALINA PARQUE LAS HELICONIAS', null, null, 'Producción de cacao semiorganico artesanal en bola', 'Producción de cacao semiorganico artesanal en bola', 'CACAO', '3167455361', '573167455361', 'fundeluz@hotmail.com', 'ANGEL MARIA QUIÑONEZ RIOS', '91485600-1', 'Natural', null, '60 MESES', 'Camara de comercio', 'KAREN CAMACHO', 'ACTIVO', 'Satisfactorio', null, 2025, '797.29', '73°09´48,3"w', '7°23´42,9"N', 'ACTUALIZO', 'Se realizo visita y se aplico ficha de verificación', null, 'NO', 'ACUEDUCTO VEREDAL', null, null, null, 'NO', 'NO', 'SI', null, 'Natural', null, 'NO', null, null, 'SI', null, null, null, null, 'NO', 'B2B', 'NO', 'NO', null, null, null, 'NO', null, null, null, null, null, null, null, null, null, true, false, false, false, true);
insert into negocios_categorias (negocio_id, categoria_oficial_id) values ('672b5be6-3791-4acb-9506-d248bb745708', (select id from categorias_oficiales where slug = 'bioproductos-servicios-sostenibles'));
insert into negocios_subcategorias (negocio_id, subcategoria_id) select '672b5be6-3791-4acb-9506-d248bb745708', id from subcategorias where slug = 'agrosistemas-sostenibles';
insert into negocios_actividades (negocio_id, actividad_productiva_id) select '672b5be6-3791-4acb-9506-d248bb745708', id from actividades_productivas where slug = 'agricultura-sostenible';
insert into negocio_puntajes (negocio_id, anio, puntaje) values ('672b5be6-3791-4acb-9506-d248bb745708', 2025, 60.0) on conflict (negocio_id, anio) do nothing;

-- HUELLA DECORATIVA
insert into negocios (id, nombre, slug, categoria_oficial_id, municipio, vereda_id, direccion, latitud, longitud, descripcion_corta, descripcion, producto, telefono, whatsapp, email, representante_legal, nit, naturaleza_juridica, delegado, tiempo_constitucion, rut_camara_comercio, responsable_cdmb, novedad, tipo_negocio_verde, codigo_marca, anio_registro, cota_msnm, este, norte, aplicacion_ficha_2025, observaciones, registro_nacional_turismo, uso_suelo, concesion_aguas, concesion_aguas_vencimiento, vertimientos, vertimientos_vencimiento, pueaa, pgris, pozo_septico, alcantarillado, ica, ica_vencimiento, invima, invima_vencimiento, certificado_tenencia_animales, buenas_practicas_agricolas, buenas_practicas_apicolas, registro_apicola, intervencion_cauce, capacidad_carga, sstt, canal_venta, exportacion, huella_carbono, fortalecimiento_tecnico, fortalecimiento_academico, fortalecimiento_financiero, internacionalizacion, certificaciones, posicionamiento_marca, beneficios_ventanilla, fortalezas_ambiental, fortalezas_social, fortalezas_economico, debilidades_ambiental, debilidades_social, debilidades_financiera, emprendimiento_verde, sello_marca, avalado, destacado, activo) values ('f83fd5b4-0284-4778-8bab-60678d5dfc68', 'HUELLA DECORATIVA', generar_slug_unico('HUELLA DECORATIVA', 'f83fd5b4-0284-4778-8bab-60678d5dfc68'), (select id from categorias_oficiales where slug = 'ecoproductos-industriales'), 'Bucaramanga', (select id from veredas where municipio = 'Bucaramanga' and slug = 'perimetro-urbano'), 'CALLE 103G # 10 - 23 BARRIO IGSABELAR', null, null, 'Artesanias con llanatas recicladas', 'Artesanias con llanatas recicladas', 'MATERAS DE LLANTAS RECICLADAS', '3123942701', '573123942701', 'huelladecorativagerencia@gmail.com', 'DIEGO VALDIVIESO TARAZONA', '91299329', null, null, null, 'Rut', 'DIEGO GUTIERREZ', 'ACTIVO', 'Intermedio', null, 2025, '917.2', '73°7´36,744"', '7°5´0,648"', 'ACTUALIZO', 'Se actualizo ficha de verificación y plan de mejora', null, null, 'ACUEDUCTO', null, null, null, 'NO', 'NO', null, 'SI', null, null, null, null, null, null, null, null, null, null, 'NO', 'B2C', 'NO', 'NO', null, null, null, 'NO', null, null, null, null, null, null, null, null, null, true, false, false, false, true);
insert into negocios_categorias (negocio_id, categoria_oficial_id) values ('f83fd5b4-0284-4778-8bab-60678d5dfc68', (select id from categorias_oficiales where slug = 'ecoproductos-industriales'));
insert into negocios_actividades (negocio_id, actividad_productiva_id) select 'f83fd5b4-0284-4778-8bab-60678d5dfc68', id from actividades_productivas where slug = 'aprovechamiento-residuos-inorganicos';
insert into negocio_puntajes (negocio_id, anio, puntaje) values ('f83fd5b4-0284-4778-8bab-60678d5dfc68', 2025, 31.1) on conflict (negocio_id, anio) do nothing;

-- LINITA ARTESANA
insert into negocios (id, nombre, slug, categoria_oficial_id, municipio, vereda_id, direccion, latitud, longitud, descripcion_corta, descripcion, producto, telefono, whatsapp, email, representante_legal, nit, naturaleza_juridica, delegado, tiempo_constitucion, rut_camara_comercio, responsable_cdmb, novedad, tipo_negocio_verde, codigo_marca, anio_registro, cota_msnm, este, norte, aplicacion_ficha_2025, observaciones, registro_nacional_turismo, uso_suelo, concesion_aguas, concesion_aguas_vencimiento, vertimientos, vertimientos_vencimiento, pueaa, pgris, pozo_septico, alcantarillado, ica, ica_vencimiento, invima, invima_vencimiento, certificado_tenencia_animales, buenas_practicas_agricolas, buenas_practicas_apicolas, registro_apicola, intervencion_cauce, capacidad_carga, sstt, canal_venta, exportacion, huella_carbono, fortalecimiento_tecnico, fortalecimiento_academico, fortalecimiento_financiero, internacionalizacion, certificaciones, posicionamiento_marca, beneficios_ventanilla, fortalezas_ambiental, fortalezas_social, fortalezas_economico, debilidades_ambiental, debilidades_social, debilidades_financiera, emprendimiento_verde, sello_marca, avalado, destacado, activo) values ('70ca158c-b5a6-4865-9ad5-3cf70033a38c', 'LINITA ARTESANA', generar_slug_unico('LINITA ARTESANA', '70ca158c-b5a6-4865-9ad5-3cf70033a38c'), (select id from categorias_oficiales where slug = 'ecoproductos-industriales'), 'Floridablanca', (select id from veredas where municipio = 'Floridablanca' and slug = 'perimetro-urbano'), 'VIA 33 # 196 - 103 PARAGUITAS CASA 1 H', null, null, 'Artesanias con retal de textil, botones reciclados y retal de zapatería', 'Artesanias con retal de textil, botones reciclados y retal de zapatería', 'ARTESANIAS CON RETAL TEXTIL (BOLSOS)', '3107903507', '573107903507', 'linitaarte@hotmail.com', 'LINA ROCIO PRADA', '63349696', null, null, null, 'Rut', 'CARINE GARCIA', 'ACTIVO', 'Basico', null, 2025, '930.8', '73°5´12,702"', '7°3´57.828', 'ACTUALIZO', 'Se actualizo ficha de verificación y plan de mejora', null, null, 'ACUEDUCTO', null, null, null, 'NO', 'NO', null, 'SI', null, null, null, null, null, null, null, null, null, null, 'NO', 'B2C', 'NO', 'NO', null, null, null, 'NO', null, null, null, null, null, null, null, null, null, true, false, false, false, true);
insert into negocios_categorias (negocio_id, categoria_oficial_id) values ('70ca158c-b5a6-4865-9ad5-3cf70033a38c', (select id from categorias_oficiales where slug = 'ecoproductos-industriales'));
insert into negocios_subcategorias (negocio_id, subcategoria_id) select '70ca158c-b5a6-4865-9ad5-3cf70033a38c', id from subcategorias where slug = 'moda-sostenible';
insert into negocios_actividades (negocio_id, actividad_productiva_id) select '70ca158c-b5a6-4865-9ad5-3cf70033a38c', id from actividades_productivas where slug = 'joyeria-artesania-bisuteria';
insert into negocio_puntajes (negocio_id, anio, puntaje) values ('70ca158c-b5a6-4865-9ad5-3cf70033a38c', 2025, 28.4) on conflict (negocio_id, anio) do nothing;

-- ENCANTO MODA PET
insert into negocios (id, nombre, slug, categoria_oficial_id, municipio, vereda_id, direccion, latitud, longitud, descripcion_corta, descripcion, producto, telefono, whatsapp, email, representante_legal, nit, naturaleza_juridica, delegado, tiempo_constitucion, rut_camara_comercio, responsable_cdmb, novedad, tipo_negocio_verde, codigo_marca, anio_registro, cota_msnm, este, norte, aplicacion_ficha_2025, observaciones, registro_nacional_turismo, uso_suelo, concesion_aguas, concesion_aguas_vencimiento, vertimientos, vertimientos_vencimiento, pueaa, pgris, pozo_septico, alcantarillado, ica, ica_vencimiento, invima, invima_vencimiento, certificado_tenencia_animales, buenas_practicas_agricolas, buenas_practicas_apicolas, registro_apicola, intervencion_cauce, capacidad_carga, sstt, canal_venta, exportacion, huella_carbono, fortalecimiento_tecnico, fortalecimiento_academico, fortalecimiento_financiero, internacionalizacion, certificaciones, posicionamiento_marca, beneficios_ventanilla, fortalezas_ambiental, fortalezas_social, fortalezas_economico, debilidades_ambiental, debilidades_social, debilidades_financiera, emprendimiento_verde, sello_marca, avalado, destacado, activo) values ('60bdbdab-62e3-48dc-b37c-52408c19952c', 'ENCANTO MODA PET', generar_slug_unico('ENCANTO MODA PET', '60bdbdab-62e3-48dc-b37c-52408c19952c'), (select id from categorias_oficiales where slug = 'ecoproductos-industriales'), 'Piedecuesta', (select id from veredas where municipio = 'Piedecuesta' and slug = 'perimetro-urbano'), 'CRA 15 # 1A - 12 LA MACARENA CASA 143', null, null, 'Ropa y accesorios para mascotas con retal textil', 'Ropa y accesorios para mascotas con retal textil', 'ACCESORIOS PARA MASCOTAS CON TELA RECICLADA', '3183122447', '573183122447', 'encantoboutiquepet@gmail.com', 'ELIANA JURLEN CAMARGO MONSALVE', '37746689-', 'Natural', null, null, 'Camara de comercio', 'CARINE GARCIA', 'ACTIVO', 'Intermedio', null, 2025, '1009', '75°5´46,726"', '7°4´19,345"', 'ACTUALIZO', 'Se actualizo ficha de verificación y plan de mejora', null, null, 'ACUEDUCTO', null, null, null, 'NO', 'NO', null, 'SI', 'Natural', null, null, null, null, null, null, null, null, null, 'NO', 'B2C', 'NO', 'NO', null, null, null, 'NO', null, null, null, null, null, null, null, null, null, true, false, false, false, true);
insert into negocios_categorias (negocio_id, categoria_oficial_id) values ('60bdbdab-62e3-48dc-b37c-52408c19952c', (select id from categorias_oficiales where slug = 'ecoproductos-industriales'));
insert into negocios_subcategorias (negocio_id, subcategoria_id) select '60bdbdab-62e3-48dc-b37c-52408c19952c', id from subcategorias where slug = 'moda-sostenible';
insert into negocios_actividades (negocio_id, actividad_productiva_id) select '60bdbdab-62e3-48dc-b37c-52408c19952c', id from actividades_productivas where slug = 'confeccion-manufactura';
insert into negocio_puntajes (negocio_id, anio, puntaje) values ('60bdbdab-62e3-48dc-b37c-52408c19952c', 2025, 33.2) on conflict (negocio_id, anio) do nothing;

-- PURA CALMA
insert into negocios (id, nombre, slug, categoria_oficial_id, municipio, vereda_id, direccion, latitud, longitud, descripcion_corta, descripcion, producto, telefono, whatsapp, email, representante_legal, nit, naturaleza_juridica, delegado, tiempo_constitucion, rut_camara_comercio, responsable_cdmb, novedad, tipo_negocio_verde, codigo_marca, anio_registro, cota_msnm, este, norte, aplicacion_ficha_2025, observaciones, registro_nacional_turismo, uso_suelo, concesion_aguas, concesion_aguas_vencimiento, vertimientos, vertimientos_vencimiento, pueaa, pgris, pozo_septico, alcantarillado, ica, ica_vencimiento, invima, invima_vencimiento, certificado_tenencia_animales, buenas_practicas_agricolas, buenas_practicas_apicolas, registro_apicola, intervencion_cauce, capacidad_carga, sstt, canal_venta, exportacion, huella_carbono, fortalecimiento_tecnico, fortalecimiento_academico, fortalecimiento_financiero, internacionalizacion, certificaciones, posicionamiento_marca, beneficios_ventanilla, fortalezas_ambiental, fortalezas_social, fortalezas_economico, debilidades_ambiental, debilidades_social, debilidades_financiera, emprendimiento_verde, sello_marca, avalado, destacado, activo) values ('65fa57f0-be7e-4172-bd73-a69d4ffba770', 'PURA CALMA', generar_slug_unico('PURA CALMA', '65fa57f0-be7e-4172-bd73-a69d4ffba770'), (select id from categorias_oficiales where slug = 'bioproductos-servicios-sostenibles'), 'Piedecuesta', (select id from veredas where municipio = 'Piedecuesta' and slug = 'perimetro-urbano'), 'PARCELA VILLA PAZ', null, null, 'Producción de jabones artesanales', 'Producción de jabones artesanales', 'JABONES ARTESANALES', '3219488287', '573219488287', 'lauraarevalojerez@gmail.com', 'LAURA AREVALO', '1098689140', null, null, null, 'NO TIENE', 'LILIANA CACERES', 'ACTIVO (RETIRADO)', 'Intermedio', null, 2025, '271°', '73°06´04.9"w', '7°01´16.4"N', 'ACTUALIZO', 'Se realizo visita y se aplico ficha de verificación', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, true, false, false, false, false);
insert into negocios_categorias (negocio_id, categoria_oficial_id) values ('65fa57f0-be7e-4172-bd73-a69d4ffba770', (select id from categorias_oficiales where slug = 'bioproductos-servicios-sostenibles'));
insert into negocios_subcategorias (negocio_id, subcategoria_id) select '65fa57f0-be7e-4172-bd73-a69d4ffba770', id from subcategorias where slug = 'agrosistemas-sostenibles';
insert into negocios_actividades (negocio_id, actividad_productiva_id) select '65fa57f0-be7e-4172-bd73-a69d4ffba770', id from actividades_productivas where slug = 'agroindustrial-no-alimentario';
insert into negocio_puntajes (negocio_id, anio, puntaje) values ('65fa57f0-be7e-4172-bd73-a69d4ffba770', 2025, 41.0) on conflict (negocio_id, anio) do nothing;

-- HERBOLARIO SANTURBAN
insert into negocios (id, nombre, slug, categoria_oficial_id, municipio, vereda_id, direccion, latitud, longitud, descripcion_corta, descripcion, producto, telefono, whatsapp, email, representante_legal, nit, naturaleza_juridica, delegado, tiempo_constitucion, rut_camara_comercio, responsable_cdmb, novedad, tipo_negocio_verde, codigo_marca, anio_registro, cota_msnm, este, norte, aplicacion_ficha_2025, observaciones, registro_nacional_turismo, uso_suelo, concesion_aguas, concesion_aguas_vencimiento, vertimientos, vertimientos_vencimiento, pueaa, pgris, pozo_septico, alcantarillado, ica, ica_vencimiento, invima, invima_vencimiento, certificado_tenencia_animales, buenas_practicas_agricolas, buenas_practicas_apicolas, registro_apicola, intervencion_cauce, capacidad_carga, sstt, canal_venta, exportacion, huella_carbono, fortalecimiento_tecnico, fortalecimiento_academico, fortalecimiento_financiero, internacionalizacion, certificaciones, posicionamiento_marca, beneficios_ventanilla, fortalezas_ambiental, fortalezas_social, fortalezas_economico, debilidades_ambiental, debilidades_social, debilidades_financiera, emprendimiento_verde, sello_marca, avalado, destacado, activo) values ('2b13056e-4ce5-4405-85f8-593cf632b2d6', 'HERBOLARIO SANTURBAN', generar_slug_unico('HERBOLARIO SANTURBAN', '2b13056e-4ce5-4405-85f8-593cf632b2d6'), (select id from categorias_oficiales where slug = 'bioproductos-servicios-sostenibles'), 'Bucaramanga', (select id from veredas where municipio = 'Bucaramanga' and slug = 'perimetro-urbano'), 'CRA 32 # 38 - 67 SOTOMAYOR', null, null, 'El modelo de negocio se basa en elaborar cosmética natural de bienestar utilizando ingredientes sostenibles y conocimientos ancestrales del Páramo de…', 'El modelo de negocio se basa en elaborar cosmética natural de bienestar utilizando ingredientes sostenibles y conocimientos ancestrales del Páramo de Santurbán. La empresa transforma materias primas naturales en brumas y aceites esenciales, trabajando con proveedores locales, procesos artesanales y prácticas responsables que conservan la biodiversidad y fortalecen la cultura del territorio.', 'INFUNSIONES', '3105001623', '573105001623', 'info@herbolariosanturban.com', 'ANGELA PIEDA GUERREO MORENO', '37843379-8', 'Natural', null, '7 MESES', 'Camara de comercio', 'ANDRES VALDERRAMA', 'ACTIVO', null, null, 2025, null, null, null, 'ACTUALIZO', 'Se realizo visita y se aplico ficha de verificación', null, null, 'ACUEDUCTO', null, null, null, 'NO', 'NO', null, 'SI', 'Natural', null, null, null, null, 'NO', null, null, null, null, 'NO', 'MIXTA', 'NO', 'NO', null, null, null, 'NO', null, null, null, null, null, null, null, null, null, true, false, false, false, true);
insert into negocios_categorias (negocio_id, categoria_oficial_id) values ('2b13056e-4ce5-4405-85f8-593cf632b2d6', (select id from categorias_oficiales where slug = 'bioproductos-servicios-sostenibles'));
insert into negocios_subcategorias (negocio_id, subcategoria_id) select '2b13056e-4ce5-4405-85f8-593cf632b2d6', id from subcategorias where slug = 'agroindustria-sostenible';
insert into negocios_actividades (negocio_id, actividad_productiva_id) select '2b13056e-4ce5-4405-85f8-593cf632b2d6', id from actividades_productivas where slug = 'agroindustrial-no-alimentario';
insert into negocio_puntajes (negocio_id, anio, puntaje) values ('2b13056e-4ce5-4405-85f8-593cf632b2d6', 2025, 54.9) on conflict (negocio_id, anio) do nothing;

-- INGENIERIA Y SERVICIOS MEDICION Y AUTOMATIZACIÓN S.A.S. (ISMA COLOMBIA S.A.S.)
insert into negocios (id, nombre, slug, categoria_oficial_id, municipio, vereda_id, direccion, latitud, longitud, descripcion_corta, descripcion, producto, telefono, whatsapp, email, representante_legal, nit, naturaleza_juridica, delegado, tiempo_constitucion, rut_camara_comercio, responsable_cdmb, novedad, tipo_negocio_verde, codigo_marca, anio_registro, cota_msnm, este, norte, aplicacion_ficha_2025, observaciones, registro_nacional_turismo, uso_suelo, concesion_aguas, concesion_aguas_vencimiento, vertimientos, vertimientos_vencimiento, pueaa, pgris, pozo_septico, alcantarillado, ica, ica_vencimiento, invima, invima_vencimiento, certificado_tenencia_animales, buenas_practicas_agricolas, buenas_practicas_apicolas, registro_apicola, intervencion_cauce, capacidad_carga, sstt, canal_venta, exportacion, huella_carbono, fortalecimiento_tecnico, fortalecimiento_academico, fortalecimiento_financiero, internacionalizacion, certificaciones, posicionamiento_marca, beneficios_ventanilla, fortalezas_ambiental, fortalezas_social, fortalezas_economico, debilidades_ambiental, debilidades_social, debilidades_financiera, emprendimiento_verde, sello_marca, avalado, destacado, activo) values ('c0c3d46c-3b8a-4266-bc09-4e8a5a5bc1d5', 'INGENIERIA Y SERVICIOS MEDICION Y AUTOMATIZACIÓN S.A.S. (ISMA COLOMBIA S.A.S.)', generar_slug_unico('INGENIERIA Y SERVICIOS MEDICION Y AUTOMATIZACIÓN S.A.S. (ISMA COLOMBIA S.A.S.)', 'c0c3d46c-3b8a-4266-bc09-4e8a5a5bc1d5'), (select id from categorias_oficiales where slug = 'calidad-ambiental'), 'Floridablanca', (select id from veredas where municipio = 'Floridablanca' and slug = 'perimetro-urbano'), 'CALLE 33 # 26 - 37 PISO 2 BARRIO CAÑAVERAL (CENTRO DE NEGOCIOS)', null, null, 'Se centra en la eficiencia energética y la innovación tecnológica, ofreciendo sistemas que optimizan el consumo eléctrico en equipos de refrigeración…', 'Se centra en la eficiencia energética y la innovación tecnológica, ofreciendo sistemas que optimizan el consumo eléctrico en equipos de refrigeración mediante monitoreo en tiempo real. Genera beneficios económicos (reducción de costos), ambientales (disminución de emisiones y huella de carbono) y sociales (empleo y cultura ambiental), aportando a los ODS y promoviendo una economía baja en carbono.', 'EFICIENCIA ENERGETICA EN EMPRESAS (SOFTWARE, EQUIPOS ELECTRONICOS)', '3173635389', '573173635389', 'ismaadmon3@gmail.com', 'CHRISTIAN JOSÉ MORALES LAZARO', '900916868-2', 'Jurídica', null, '126 MESES', 'Camara de comercio', 'ANDRES VALDERRAMA', 'ACTIVO', null, null, 2025, null, null, null, 'ACTUALIZO', 'Se realizo visita y se aplico ficha de verificación', null, null, 'ACUEDUCTO', null, null, null, 'NO', 'NO', null, 'SI', 'Jurídica', null, null, null, null, null, null, null, null, null, 'NO', 'MIXTA', 'NO', 'NO', null, null, null, 'NO', null, null, null, null, null, null, null, null, null, true, false, false, false, true);
insert into negocios_categorias (negocio_id, categoria_oficial_id) values ('c0c3d46c-3b8a-4266-bc09-4e8a5a5bc1d5', (select id from categorias_oficiales where slug = 'calidad-ambiental'));
insert into negocios_subcategorias (negocio_id, subcategoria_id) select 'c0c3d46c-3b8a-4266-bc09-4e8a5a5bc1d5', id from subcategorias where slug = 'tecnologias-verdes';
insert into negocios_actividades (negocio_id, actividad_productiva_id) select 'c0c3d46c-3b8a-4266-bc09-4e8a5a5bc1d5', id from actividades_productivas where slug = 'tecnologias-informacion-ambiental';
insert into negocio_puntajes (negocio_id, anio, puntaje) values ('c0c3d46c-3b8a-4266-bc09-4e8a5a5bc1d5', 2025, 59.9) on conflict (negocio_id, anio) do nothing;

-- FRUTOX S.A.S
insert into negocios (id, nombre, slug, categoria_oficial_id, municipio, vereda_id, direccion, latitud, longitud, descripcion_corta, descripcion, producto, telefono, whatsapp, email, representante_legal, nit, naturaleza_juridica, delegado, tiempo_constitucion, rut_camara_comercio, responsable_cdmb, novedad, tipo_negocio_verde, codigo_marca, anio_registro, cota_msnm, este, norte, aplicacion_ficha_2025, observaciones, registro_nacional_turismo, uso_suelo, concesion_aguas, concesion_aguas_vencimiento, vertimientos, vertimientos_vencimiento, pueaa, pgris, pozo_septico, alcantarillado, ica, ica_vencimiento, invima, invima_vencimiento, certificado_tenencia_animales, buenas_practicas_agricolas, buenas_practicas_apicolas, registro_apicola, intervencion_cauce, capacidad_carga, sstt, canal_venta, exportacion, huella_carbono, fortalecimiento_tecnico, fortalecimiento_academico, fortalecimiento_financiero, internacionalizacion, certificaciones, posicionamiento_marca, beneficios_ventanilla, fortalezas_ambiental, fortalezas_social, fortalezas_economico, debilidades_ambiental, debilidades_social, debilidades_financiera, emprendimiento_verde, sello_marca, avalado, destacado, activo) values ('2f0a4a43-9aa4-4aa9-b715-262f477706ce', 'FRUTOX S.A.S', generar_slug_unico('FRUTOX S.A.S', '2f0a4a43-9aa4-4aa9-b715-262f477706ce'), (select id from categorias_oficiales where slug = 'bioproductos-servicios-sostenibles'), 'Bucaramanga', (select id from veredas where municipio = 'Bucaramanga' and slug = 'perimetro-urbano'), 'CENTROABASTOS BODEGA 1 3 63', null, null, 'Elaboración y comercialización de pulpas de frutas y otros derivados de las mismas.', 'Elaboración y comercialización de pulpas de frutas y otros derivados de las mismas.', 'PULPA DE LIMÓN Y PIÑA', '3102426554', '573102426554', 'frutoxcolombia@gmail.com', 'MARIA LUISA PEREIRA DÍAZ', '901804661-8', 'Jurídica', null, '34 MESES', 'Camara de comercio', 'XIMENA REYES', 'ACTIVO', 'Satisfactorio', null, 2025, null, '-73166919', '7103487', 'ACTUALIZO', 'Se realizo visita y se aplico ficha de verificacion', null, 'SI', 'ACUEDUCTO', null, null, null, 'NO', 'NO', null, 'SI', 'Jurídica', null, 'SI', '2032-08-01', null, 'NO', null, null, null, null, 'NO', 'MIXTA', 'NO', 'NO', null, null, null, 'NO', null, null, null, null, null, null, null, null, null, false, false, true, false, true);
insert into negocios_categorias (negocio_id, categoria_oficial_id) values ('2f0a4a43-9aa4-4aa9-b715-262f477706ce', (select id from categorias_oficiales where slug = 'bioproductos-servicios-sostenibles'));
insert into negocios_subcategorias (negocio_id, subcategoria_id) select '2f0a4a43-9aa4-4aa9-b715-262f477706ce', id from subcategorias where slug = 'agroindustria-sostenible';
insert into negocios_actividades (negocio_id, actividad_productiva_id) select '2f0a4a43-9aa4-4aa9-b715-262f477706ce', id from actividades_productivas where slug = 'agroindustrial-alimentario';
insert into negocio_puntajes (negocio_id, anio, puntaje) values ('2f0a4a43-9aa4-4aa9-b715-262f477706ce', 2025, 67.1) on conflict (negocio_id, anio) do nothing;

-- BIABONOS Y PRODUCTOS DE LA TIERRA
insert into negocios (id, nombre, slug, categoria_oficial_id, municipio, vereda_id, direccion, latitud, longitud, descripcion_corta, descripcion, producto, telefono, whatsapp, email, representante_legal, nit, naturaleza_juridica, delegado, tiempo_constitucion, rut_camara_comercio, responsable_cdmb, novedad, tipo_negocio_verde, codigo_marca, anio_registro, cota_msnm, este, norte, aplicacion_ficha_2025, observaciones, registro_nacional_turismo, uso_suelo, concesion_aguas, concesion_aguas_vencimiento, vertimientos, vertimientos_vencimiento, pueaa, pgris, pozo_septico, alcantarillado, ica, ica_vencimiento, invima, invima_vencimiento, certificado_tenencia_animales, buenas_practicas_agricolas, buenas_practicas_apicolas, registro_apicola, intervencion_cauce, capacidad_carga, sstt, canal_venta, exportacion, huella_carbono, fortalecimiento_tecnico, fortalecimiento_academico, fortalecimiento_financiero, internacionalizacion, certificaciones, posicionamiento_marca, beneficios_ventanilla, fortalezas_ambiental, fortalezas_social, fortalezas_economico, debilidades_ambiental, debilidades_social, debilidades_financiera, emprendimiento_verde, sello_marca, avalado, destacado, activo) values ('126cb2bf-e017-4122-bf39-629e24d10f08', 'BIABONOS Y PRODUCTOS DE LA TIERRA', generar_slug_unico('BIABONOS Y PRODUCTOS DE LA TIERRA', '126cb2bf-e017-4122-bf39-629e24d10f08'), (select id from categorias_oficiales where slug = 'bioproductos-servicios-sostenibles'), 'Piedecuesta', (select id from veredas where municipio = 'Piedecuesta' and slug = 'el-duende'), 'FINCA VILLA PEPA VEREDA EL DUENDE, MUNICIPIO DE PIEDECUESTA', null, null, 'Produce lombrinaza y compost biológico elaborados a partir de residuos orgánicos de la finca, restos de cultivos, afrecho de café y biológicos naturales…', 'Produce lombrinaza y compost biológico elaborados a partir de residuos orgánicos de la finca, restos de cultivos, afrecho de café y biológicos naturales como SAVIA. Es un abono 100% orgánico, rico en nutrientes, que mejora la estructura del suelo, aumenta la fertilidad y favorece el desarrollo saludable de cultivos y jardines sin emplear químicos.', 'PRODUCCION DE HORTALIZAS', '3208559750', '573208559750', 'marthalilianarodriguez730@gmail.com', 'MARTHA LILIANA RODRIGUEZ ARENAS', '37619730', null, null, null, 'Rut', 'LILIANA CACERES', 'ACTIVO', 'Intermedio', null, 2025, null, '73°06´5.592"', '6°89´1.809"', 'ACTUALIZO', 'Se realizo visita y se aplico ficha de verificacion', null, 'NO', 'NO', null, 'NO', null, 'NO', 'NO', 'NO', null, null, null, null, null, null, 'NO', null, null, null, null, 'NO', 'B2B', 'NO', 'NO', null, null, null, 'NO', null, null, null, null, null, null, null, null, null, true, false, false, false, true);
insert into negocios_categorias (negocio_id, categoria_oficial_id) values ('126cb2bf-e017-4122-bf39-629e24d10f08', (select id from categorias_oficiales where slug = 'bioproductos-servicios-sostenibles'));
insert into negocios_subcategorias (negocio_id, subcategoria_id) select '126cb2bf-e017-4122-bf39-629e24d10f08', id from subcategorias where slug = 'agrosistemas-sostenibles';
insert into negocios_actividades (negocio_id, actividad_productiva_id) select '126cb2bf-e017-4122-bf39-629e24d10f08', id from actividades_productivas where slug = 'agricultura-organica';
insert into negocio_puntajes (negocio_id, anio, puntaje) values ('126cb2bf-e017-4122-bf39-629e24d10f08', 2025, 47.4) on conflict (negocio_id, anio) do nothing;

-- SETAS DE LA MESA
insert into negocios (id, nombre, slug, categoria_oficial_id, municipio, vereda_id, direccion, latitud, longitud, descripcion_corta, descripcion, producto, telefono, whatsapp, email, representante_legal, nit, naturaleza_juridica, delegado, tiempo_constitucion, rut_camara_comercio, responsable_cdmb, novedad, tipo_negocio_verde, codigo_marca, anio_registro, cota_msnm, este, norte, aplicacion_ficha_2025, observaciones, registro_nacional_turismo, uso_suelo, concesion_aguas, concesion_aguas_vencimiento, vertimientos, vertimientos_vencimiento, pueaa, pgris, pozo_septico, alcantarillado, ica, ica_vencimiento, invima, invima_vencimiento, certificado_tenencia_animales, buenas_practicas_agricolas, buenas_practicas_apicolas, registro_apicola, intervencion_cauce, capacidad_carga, sstt, canal_venta, exportacion, huella_carbono, fortalecimiento_tecnico, fortalecimiento_academico, fortalecimiento_financiero, internacionalizacion, certificaciones, posicionamiento_marca, beneficios_ventanilla, fortalezas_ambiental, fortalezas_social, fortalezas_economico, debilidades_ambiental, debilidades_social, debilidades_financiera, emprendimiento_verde, sello_marca, avalado, destacado, activo) values ('19c8aea0-8aa9-4025-a85b-0b93bdc11e6b', 'SETAS DE LA MESA', generar_slug_unico('SETAS DE LA MESA', '19c8aea0-8aa9-4025-a85b-0b93bdc11e6b'), (select id from categorias_oficiales where slug = 'bioproductos-servicios-sostenibles'), 'Piedecuesta', (select id from veredas where municipio = 'Piedecuesta' and slug = 'el-duende'), 'FINCA VILLA PEPA VEREDA EL DUENDE, MUNICIPIO DE PIEDECUESTA', null, null, 'Setas de la Mesa se dedica a la producción y comercialización de orellanas y derivados, incluyendo orellanas frescas, carne molida vegetal a base de hongo,…', 'Setas de la Mesa se dedica a la producción y comercialización de orellanas y derivados, incluyendo orellanas frescas, carne molida vegetal a base de hongo, hamburguesas de orellana y antipastos artesanales. Su actividad integra procesos sostenibles de cultivo y transformación para ofrecer alimentos saludables y de origen responsable.', 'ORELLANAS FRESCAS', '3144751018', '573144751018', 'albitaluci1589@gmail.com', 'ALBA LUCÍA SOLANO RÍOS', '1026261895', 'Natural', null, null, 'Rut', 'LILIANA CACERES', 'ACTIVO', 'Intermedio', null, 2025, '1722', '78°06´5713"', '6°89´3093"', 'ACTUALIZO', 'Se realizo visita y se aplico ficha de verificacion', null, 'NO', 'NO', null, 'NO', null, 'NO', 'NO', 'NO', null, 'Natural', null, 'NO', null, null, 'NO', null, null, null, null, 'NO', 'B2B', 'NO', 'NO', null, null, null, 'NO', null, null, null, null, null, null, null, null, null, true, false, false, false, true);
insert into negocios_categorias (negocio_id, categoria_oficial_id) values ('19c8aea0-8aa9-4025-a85b-0b93bdc11e6b', (select id from categorias_oficiales where slug = 'bioproductos-servicios-sostenibles'));
insert into negocios_subcategorias (negocio_id, subcategoria_id) select '19c8aea0-8aa9-4025-a85b-0b93bdc11e6b', id from subcategorias where slug = 'agroindustria-sostenible';
insert into negocios_actividades (negocio_id, actividad_productiva_id) select '19c8aea0-8aa9-4025-a85b-0b93bdc11e6b', id from actividades_productivas where slug = 'agroindustrial-alimentario';
insert into negocio_puntajes (negocio_id, anio, puntaje) values ('19c8aea0-8aa9-4025-a85b-0b93bdc11e6b', 2025, 48.7) on conflict (negocio_id, anio) do nothing;

-- MY BEE HAPPY
insert into negocios (id, nombre, slug, categoria_oficial_id, municipio, vereda_id, direccion, latitud, longitud, descripcion_corta, descripcion, producto, telefono, whatsapp, email, representante_legal, nit, naturaleza_juridica, delegado, tiempo_constitucion, rut_camara_comercio, responsable_cdmb, novedad, tipo_negocio_verde, codigo_marca, anio_registro, cota_msnm, este, norte, aplicacion_ficha_2025, observaciones, registro_nacional_turismo, uso_suelo, concesion_aguas, concesion_aguas_vencimiento, vertimientos, vertimientos_vencimiento, pueaa, pgris, pozo_septico, alcantarillado, ica, ica_vencimiento, invima, invima_vencimiento, certificado_tenencia_animales, buenas_practicas_agricolas, buenas_practicas_apicolas, registro_apicola, intervencion_cauce, capacidad_carga, sstt, canal_venta, exportacion, huella_carbono, fortalecimiento_tecnico, fortalecimiento_academico, fortalecimiento_financiero, internacionalizacion, certificaciones, posicionamiento_marca, beneficios_ventanilla, fortalezas_ambiental, fortalezas_social, fortalezas_economico, debilidades_ambiental, debilidades_social, debilidades_financiera, emprendimiento_verde, sello_marca, avalado, destacado, activo) values ('3ca6437f-0295-4aec-afec-459a016bfd34', 'MY BEE HAPPY', generar_slug_unico('MY BEE HAPPY', '3ca6437f-0295-4aec-afec-459a016bfd34'), (select id from categorias_oficiales where slug = 'pendiente-clasificar'), 'Piedecuesta', (select id from veredas where municipio = 'Piedecuesta' and slug = 'la-colombiana'), 'CORREGIMIENTO UMPALA FINCA EL TUNA', null, null, null, null, 'MIEL Y POLEN DE ABEJAS', '3175557537', '573175557537', 'condecondewillian@gmail.com', 'WILLIAM CONDE CONDE', '91353589', null, null, null, null, 'HEINER ORTIZ', 'ACTIVO', null, null, 2025, null, null, null, null, 'No se ha realizado visita', null, 'NO', 'NO', null, 'NO', null, 'NO', 'NO', 'NO', null, null, null, 'NO', null, null, null, 'NO', 'NO', null, null, 'NO', 'B2C', 'NO', 'NO', null, null, null, 'NO', null, null, null, null, null, null, null, null, null, true, false, false, false, true);
insert into negocios_categorias (negocio_id, categoria_oficial_id) values ('3ca6437f-0295-4aec-afec-459a016bfd34', (select id from categorias_oficiales where slug = 'pendiente-clasificar'));

-- MOISSA CHOCOLATE
insert into negocios (id, nombre, slug, categoria_oficial_id, municipio, vereda_id, direccion, latitud, longitud, descripcion_corta, descripcion, producto, telefono, whatsapp, email, representante_legal, nit, naturaleza_juridica, delegado, tiempo_constitucion, rut_camara_comercio, responsable_cdmb, novedad, tipo_negocio_verde, codigo_marca, anio_registro, cota_msnm, este, norte, aplicacion_ficha_2025, observaciones, registro_nacional_turismo, uso_suelo, concesion_aguas, concesion_aguas_vencimiento, vertimientos, vertimientos_vencimiento, pueaa, pgris, pozo_septico, alcantarillado, ica, ica_vencimiento, invima, invima_vencimiento, certificado_tenencia_animales, buenas_practicas_agricolas, buenas_practicas_apicolas, registro_apicola, intervencion_cauce, capacidad_carga, sstt, canal_venta, exportacion, huella_carbono, fortalecimiento_tecnico, fortalecimiento_academico, fortalecimiento_financiero, internacionalizacion, certificaciones, posicionamiento_marca, beneficios_ventanilla, fortalezas_ambiental, fortalezas_social, fortalezas_economico, debilidades_ambiental, debilidades_social, debilidades_financiera, emprendimiento_verde, sello_marca, avalado, destacado, activo) values ('3112a895-292d-42cc-b438-c188bebe4b6a', 'MOISSA CHOCOLATE', generar_slug_unico('MOISSA CHOCOLATE', '3112a895-292d-42cc-b438-c188bebe4b6a'), (select id from categorias_oficiales where slug = 'bioproductos-servicios-sostenibles'), 'Piedecuesta', (select id from veredas where municipio = 'Piedecuesta' and slug = 'umpala'), 'VEREDA UMPALA FINCA EL PUENTE - FINCA LAS BRISAS CALLEJUELA 240 VEREDA UMPALA', null, null, 'Cultivo y Producción de Cacao Orgánico:  siembra, cultivo, mantenimiento, cosecha y comercialización de granos de cacao y transformación en Chocolate de Mesa', 'Cultivo y Producción de Cacao Orgánico:  siembra, cultivo, mantenimiento, cosecha y comercialización de granos de cacao y transformación en Chocolate de Mesa', 'CHOCOLATE DE MESA', '3246647389', '573246647389', 'angelmpz9@gmail.com', 'ANGEL MAURICIO PORRAS ZABALA', '91498346-1', 'Natural', null, '13 MESES', 'Camara de comercio', 'NATALY RAMIREZ', 'ACTIVO', null, null, 2025, null, null, null, null, 'No se ha realizado visita', null, 'SI', 'NO', null, 'NO', null, 'NO', 'NO', 'SI', null, 'Natural', null, 'SI', '2036-03-28', null, 'NO', null, null, null, null, 'NO', 'B2C', 'NO', 'NO', null, null, null, 'NO', null, null, null, null, null, null, null, null, null, true, false, false, false, true);
insert into negocios_categorias (negocio_id, categoria_oficial_id) values ('3112a895-292d-42cc-b438-c188bebe4b6a', (select id from categorias_oficiales where slug = 'bioproductos-servicios-sostenibles'));
insert into negocios_subcategorias (negocio_id, subcategoria_id) select '3112a895-292d-42cc-b438-c188bebe4b6a', id from subcategorias where slug = 'agroindustria-sostenible';
insert into negocios_actividades (negocio_id, actividad_productiva_id) select '3112a895-292d-42cc-b438-c188bebe4b6a', id from actividades_productivas where slug = 'agroindustrial-alimentario';

-- ASOSICACIÓN AGROSOTONORTE
insert into negocios (id, nombre, slug, categoria_oficial_id, municipio, vereda_id, direccion, latitud, longitud, descripcion_corta, descripcion, producto, telefono, whatsapp, email, representante_legal, nit, naturaleza_juridica, delegado, tiempo_constitucion, rut_camara_comercio, responsable_cdmb, novedad, tipo_negocio_verde, codigo_marca, anio_registro, cota_msnm, este, norte, aplicacion_ficha_2025, observaciones, registro_nacional_turismo, uso_suelo, concesion_aguas, concesion_aguas_vencimiento, vertimientos, vertimientos_vencimiento, pueaa, pgris, pozo_septico, alcantarillado, ica, ica_vencimiento, invima, invima_vencimiento, certificado_tenencia_animales, buenas_practicas_agricolas, buenas_practicas_apicolas, registro_apicola, intervencion_cauce, capacidad_carga, sstt, canal_venta, exportacion, huella_carbono, fortalecimiento_tecnico, fortalecimiento_academico, fortalecimiento_financiero, internacionalizacion, certificaciones, posicionamiento_marca, beneficios_ventanilla, fortalezas_ambiental, fortalezas_social, fortalezas_economico, debilidades_ambiental, debilidades_social, debilidades_financiera, emprendimiento_verde, sello_marca, avalado, destacado, activo) values ('ab3ffb62-92a7-472b-8d4e-0c97057ecb08', 'ASOSICACIÓN AGROSOTONORTE', generar_slug_unico('ASOSICACIÓN AGROSOTONORTE', 'ab3ffb62-92a7-472b-8d4e-0c97057ecb08'), (select id from categorias_oficiales where slug = 'bioproductos-servicios-sostenibles'), 'Suratá', (select id from veredas where municipio = 'Suratá' and slug = 'el-porvenir'), 'FINCA VILLA NUEVA 2 VEREDA EL PORVENIR, SURATA', null, null, 'Producción y comercializacion de miel organica', 'Producción y comercializacion de miel organica', 'MIEL ORGANICA', '3175386172', '573175386172', 'agrosotonorte@gmail.com', 'VIDAL RAMIREZ CACUA', '901992380-8', 'Jurídica', null, '3 MESES', 'Camara de comercio', 'SILVIA VALDIVIESO', 'ACTIVO', 'Inicial', null, 2025, '2.034°', '72°58´49,5"w', '7°23´36,4" n', 'ACTUALIZO', 'Se realizo visita y se aplico ficha de verificación', null, 'NO', 'NO', null, 'NO', null, 'NO', 'NO', 'SI', null, 'Jurídica', null, null, null, null, null, 'NO', 'NO', null, null, 'NO', 'B2C', 'NO', 'NO', null, null, null, 'NO', null, null, null, null, null, null, null, null, null, true, false, false, false, true);
insert into negocios_categorias (negocio_id, categoria_oficial_id) values ('ab3ffb62-92a7-472b-8d4e-0c97057ecb08', (select id from categorias_oficiales where slug = 'bioproductos-servicios-sostenibles'));
insert into negocios_subcategorias (negocio_id, subcategoria_id) select 'ab3ffb62-92a7-472b-8d4e-0c97057ecb08', id from subcategorias where slug = 'agrosistemas-sostenibles';
insert into negocios_actividades (negocio_id, actividad_productiva_id) select 'ab3ffb62-92a7-472b-8d4e-0c97057ecb08', id from actividades_productivas where slug = 'agricultura-sostenible';

-- CHOCOPASSION
insert into negocios (id, nombre, slug, categoria_oficial_id, municipio, vereda_id, direccion, latitud, longitud, descripcion_corta, descripcion, producto, telefono, whatsapp, email, representante_legal, nit, naturaleza_juridica, delegado, tiempo_constitucion, rut_camara_comercio, responsable_cdmb, novedad, tipo_negocio_verde, codigo_marca, anio_registro, cota_msnm, este, norte, aplicacion_ficha_2025, observaciones, registro_nacional_turismo, uso_suelo, concesion_aguas, concesion_aguas_vencimiento, vertimientos, vertimientos_vencimiento, pueaa, pgris, pozo_septico, alcantarillado, ica, ica_vencimiento, invima, invima_vencimiento, certificado_tenencia_animales, buenas_practicas_agricolas, buenas_practicas_apicolas, registro_apicola, intervencion_cauce, capacidad_carga, sstt, canal_venta, exportacion, huella_carbono, fortalecimiento_tecnico, fortalecimiento_academico, fortalecimiento_financiero, internacionalizacion, certificaciones, posicionamiento_marca, beneficios_ventanilla, fortalezas_ambiental, fortalezas_social, fortalezas_economico, debilidades_ambiental, debilidades_social, debilidades_financiera, emprendimiento_verde, sello_marca, avalado, destacado, activo) values ('c590c62d-ab60-430e-866d-49d4c4bcb250', 'CHOCOPASSION', generar_slug_unico('CHOCOPASSION', 'c590c62d-ab60-430e-866d-49d4c4bcb250'), (select id from categorias_oficiales where slug = 'bioproductos-servicios-sostenibles'), 'Lebrija', (select id from veredas where municipio = 'Lebrija' and slug = 'perimetro-urbano'), 'CARRERA 5 # 28-05 BUCARAMANGA', null, null, 'Chocopassio se dedica a la transformación del cacao en productos derivados como chocolate de mesa endulzado con panela, cacao 100% y preparaciones…', 'Chocopassio se dedica a la transformación del cacao en productos derivados como chocolate de mesa endulzado con panela, cacao 100% y preparaciones artesanales basadas en subproductos del cacao, como barras de chocolate con ajonjolí y fruta deshidratada cubierta de chocolate. Su actividad incluye la compra de cacao a productores locales, el procesamiento artesanal de los granos y la elaboración de alimentos naturales y de valor agregado, enfocados en prácticas sostenibles y en el aprovechamiento integral del fruto.', 'CHOCOLATE DE MESA', '3052991276', '573052991276', 'yulygomez945@gmail.com', 'YULY VIVIANA GÓMEZ PARRA', '901967591-1', 'Jurídica', null, null, 'Camara de comercio', 'DIEGO GUTIERREZ', 'ACTIVO', 'Intermedio', null, 2025, null, null, null, 'ACTUALIZO', 'Se realizo visita y se aplico ficha de verificacion', null, 'NO', 'ACUEDUCTO VEREDAL', null, null, null, 'NO', 'NO', null, 'SI', 'Jurídica', null, 'NO', null, null, 'NO', null, null, null, null, 'NO', 'MIXTA', 'NO', 'NO', null, null, null, 'NO', null, null, null, null, null, null, null, null, null, true, false, false, false, true);
insert into negocios_categorias (negocio_id, categoria_oficial_id) values ('c590c62d-ab60-430e-866d-49d4c4bcb250', (select id from categorias_oficiales where slug = 'bioproductos-servicios-sostenibles'));
insert into negocios_subcategorias (negocio_id, subcategoria_id) select 'c590c62d-ab60-430e-866d-49d4c4bcb250', id from subcategorias where slug = 'agroindustria-sostenible';
insert into negocios_actividades (negocio_id, actividad_productiva_id) select 'c590c62d-ab60-430e-866d-49d4c4bcb250', id from actividades_productivas where slug = 'agroindustrial-alimentario';
insert into negocio_puntajes (negocio_id, anio, puntaje) values ('c590c62d-ab60-430e-866d-49d4c4bcb250', 2025, 43.3) on conflict (negocio_id, anio) do nothing;

-- SOLUTIONS BIOTECHNOLOGY S.A.S BIC
insert into negocios (id, nombre, slug, categoria_oficial_id, municipio, vereda_id, direccion, latitud, longitud, descripcion_corta, descripcion, producto, telefono, whatsapp, email, representante_legal, nit, naturaleza_juridica, delegado, tiempo_constitucion, rut_camara_comercio, responsable_cdmb, novedad, tipo_negocio_verde, codigo_marca, anio_registro, cota_msnm, este, norte, aplicacion_ficha_2025, observaciones, registro_nacional_turismo, uso_suelo, concesion_aguas, concesion_aguas_vencimiento, vertimientos, vertimientos_vencimiento, pueaa, pgris, pozo_septico, alcantarillado, ica, ica_vencimiento, invima, invima_vencimiento, certificado_tenencia_animales, buenas_practicas_agricolas, buenas_practicas_apicolas, registro_apicola, intervencion_cauce, capacidad_carga, sstt, canal_venta, exportacion, huella_carbono, fortalecimiento_tecnico, fortalecimiento_academico, fortalecimiento_financiero, internacionalizacion, certificaciones, posicionamiento_marca, beneficios_ventanilla, fortalezas_ambiental, fortalezas_social, fortalezas_economico, debilidades_ambiental, debilidades_social, debilidades_financiera, emprendimiento_verde, sello_marca, avalado, destacado, activo) values ('4781ca77-742a-4ed9-a98f-c78289c2b512', 'SOLUTIONS BIOTECHNOLOGY S.A.S BIC', generar_slug_unico('SOLUTIONS BIOTECHNOLOGY S.A.S BIC', '4781ca77-742a-4ed9-a98f-c78289c2b512'), (select id from categorias_oficiales where slug = 'ecoproductos-industriales'), 'Piedecuesta', (select id from veredas where municipio = 'Piedecuesta' and slug = 'diamante'), 'VEREDA EL DIAMANTE PIEDECUESTA', null, null, 'Se dedica a la bioconversión de residuos orgánicos mediante la reproducción y cultivo de la mosca soldado negra (Hermetia illucens). La empresa transforma…', 'Se dedica a la bioconversión de residuos orgánicos mediante la reproducción y cultivo de la mosca soldado negra (Hermetia illucens). La empresa transforma materiales orgánicos en productos de valor agregado como compost, biofertilizantes y proteína de alta calidad para alimentación animal. Su actividad integra procesos de economía circular orientados a la descarbonización y al aprovechamiento de subproductos.', 'GESTION DE RESIDUOS ORGÁNICOS MEDIANTE BIOCONVERSIÓN CON MOSCA SOLDADO PARA PRODUCIR COMPOST Y PROTEÍNA SOSTENIBLE.', '3154740027', '573154740027', 'Info@solucionesbio.com', 'JOSE ARMANDO RAMIREZ RAMIREZ', '901652873-9', 'Jurídica', null, '43 meses', 'Camara de comercio', 'DIANA NAVARRO', 'ACTIVO', 'Intermedio', null, 2025, null, null, null, 'ACTUALIZO', 'Se realizo visita y se actualizo ficha de verificacion', null, 'NO', 'NO', null, 'NO', null, 'NO', 'SI', 'NO', null, 'Jurídica', null, null, null, null, null, null, null, null, null, 'NO', 'B2B', 'NO', 'NO', null, null, null, 'NO', null, null, null, null, null, null, null, null, null, true, false, false, false, true);
insert into negocios_categorias (negocio_id, categoria_oficial_id) values ('4781ca77-742a-4ed9-a98f-c78289c2b512', (select id from categorias_oficiales where slug = 'ecoproductos-industriales'));
insert into negocios_actividades (negocio_id, actividad_productiva_id) select '4781ca77-742a-4ed9-a98f-c78289c2b512', id from actividades_productivas where slug = 'aprovechamiento-residuos-organicos';
insert into negocio_puntajes (negocio_id, anio, puntaje) values ('4781ca77-742a-4ed9-a98f-c78289c2b512', 2025, 40.8) on conflict (negocio_id, anio) do nothing;

-- AUROMA VELAS Y JABONES ARTESANALES
insert into negocios (id, nombre, slug, categoria_oficial_id, municipio, vereda_id, direccion, latitud, longitud, descripcion_corta, descripcion, producto, telefono, whatsapp, email, representante_legal, nit, naturaleza_juridica, delegado, tiempo_constitucion, rut_camara_comercio, responsable_cdmb, novedad, tipo_negocio_verde, codigo_marca, anio_registro, cota_msnm, este, norte, aplicacion_ficha_2025, observaciones, registro_nacional_turismo, uso_suelo, concesion_aguas, concesion_aguas_vencimiento, vertimientos, vertimientos_vencimiento, pueaa, pgris, pozo_septico, alcantarillado, ica, ica_vencimiento, invima, invima_vencimiento, certificado_tenencia_animales, buenas_practicas_agricolas, buenas_practicas_apicolas, registro_apicola, intervencion_cauce, capacidad_carga, sstt, canal_venta, exportacion, huella_carbono, fortalecimiento_tecnico, fortalecimiento_academico, fortalecimiento_financiero, internacionalizacion, certificaciones, posicionamiento_marca, beneficios_ventanilla, fortalezas_ambiental, fortalezas_social, fortalezas_economico, debilidades_ambiental, debilidades_social, debilidades_financiera, emprendimiento_verde, sello_marca, avalado, destacado, activo) values ('79dd9e75-dc1f-415a-94ae-95ed917cd266', 'AUROMA VELAS Y JABONES ARTESANALES', generar_slug_unico('AUROMA VELAS Y JABONES ARTESANALES', '79dd9e75-dc1f-415a-94ae-95ed917cd266'), (select id from categorias_oficiales where slug = 'pendiente-clasificar'), 'Floridablanca', (select id from veredas where municipio = 'Floridablanca' and slug = 'perimetro-urbano'), 'CRA 3 NO. 2 - 192 CASA 33', null, null, null, null, 'VELAS Y JABONES ARTESANALES', '3114823425', '573114823425', 'aurorapemo@outlook.com', 'AURORA PEDREROS', null, null, null, null, null, 'JENNIFER BLANCO', 'ACTIVO', null, null, 2026, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, true, false, false, false, true);
insert into negocios_categorias (negocio_id, categoria_oficial_id) values ('79dd9e75-dc1f-415a-94ae-95ed917cd266', (select id from categorias_oficiales where slug = 'pendiente-clasificar'));

-- CAFÉ LOS GUANES
insert into negocios (id, nombre, slug, categoria_oficial_id, municipio, vereda_id, direccion, latitud, longitud, descripcion_corta, descripcion, producto, telefono, whatsapp, email, representante_legal, nit, naturaleza_juridica, delegado, tiempo_constitucion, rut_camara_comercio, responsable_cdmb, novedad, tipo_negocio_verde, codigo_marca, anio_registro, cota_msnm, este, norte, aplicacion_ficha_2025, observaciones, registro_nacional_turismo, uso_suelo, concesion_aguas, concesion_aguas_vencimiento, vertimientos, vertimientos_vencimiento, pueaa, pgris, pozo_septico, alcantarillado, ica, ica_vencimiento, invima, invima_vencimiento, certificado_tenencia_animales, buenas_practicas_agricolas, buenas_practicas_apicolas, registro_apicola, intervencion_cauce, capacidad_carga, sstt, canal_venta, exportacion, huella_carbono, fortalecimiento_tecnico, fortalecimiento_academico, fortalecimiento_financiero, internacionalizacion, certificaciones, posicionamiento_marca, beneficios_ventanilla, fortalezas_ambiental, fortalezas_social, fortalezas_economico, debilidades_ambiental, debilidades_social, debilidades_financiera, emprendimiento_verde, sello_marca, avalado, destacado, activo) values ('700a93bc-14c2-413c-8509-2f47e7d6aac9', 'CAFÉ LOS GUANES', generar_slug_unico('CAFÉ LOS GUANES', '700a93bc-14c2-413c-8509-2f47e7d6aac9'), (select id from categorias_oficiales where slug = 'bioproductos-servicios-sostenibles'), 'Piedecuesta', (select id from veredas where municipio = 'Piedecuesta' and slug = 'san-miguel'), 'VEREDA SAN MIGUEL BAJOS PARCELA LOS GUNES', null, null, 'Café Los Guanes es un emprendimiento familiar ubicado en la vereda San Miguel Bajo, Piedecuesta (Santander), dedicado al cultivo, transformación y…', 'Café Los Guanes es un emprendimiento familiar ubicado en la vereda San Miguel Bajo, Piedecuesta (Santander), dedicado al cultivo, transformación y comercialización de café artesanal. Basado en una tradición cafetera que se remonta a 1948, su modelo de negocio integra toda la cadena productiva, desde la siembra y cosecha hasta el beneficio, tueste, molienda, empaque y venta de café en grano y molido. Su propuesta de valor se centra en ofrecer un café de origen, natural y de alta calidad, destacándose por su aroma, sabor y producción artesanal bajo el lema: “Del campo al comedor, Café Los Guanes, lo mejor”.', 'CAFÉ ORGÁNICO', '3155426673', '573155426673', 'perezardilajulianleonardo@gmail.com', 'JULIAN LEONARDO PEREZ ARDILA', '1005297638-2', 'Natural', null, null, 'Camara de comercio', 'SUJEY DÍAZ', 'ACTIVO', null, null, 2026, null, null, null, null, null, null, 'NO', 'NO', null, 'NO', null, 'NO', 'NO', 'NO', null, 'Natural', null, 'NO', null, null, 'NO', null, null, null, null, 'NO', 'B2C', 'NO', 'NO', null, null, null, 'NO', null, null, null, null, null, null, null, null, null, true, false, false, false, true);
insert into negocios_categorias (negocio_id, categoria_oficial_id) values ('700a93bc-14c2-413c-8509-2f47e7d6aac9', (select id from categorias_oficiales where slug = 'bioproductos-servicios-sostenibles'));
insert into negocios_subcategorias (negocio_id, subcategoria_id) select '700a93bc-14c2-413c-8509-2f47e7d6aac9', id from subcategorias where slug = 'agroindustria-sostenible';
insert into negocios_actividades (negocio_id, actividad_productiva_id) select '700a93bc-14c2-413c-8509-2f47e7d6aac9', id from actividades_productivas where slug = 'agroindustrial-alimentario';

-- NUTRATECH
insert into negocios (id, nombre, slug, categoria_oficial_id, municipio, vereda_id, direccion, latitud, longitud, descripcion_corta, descripcion, producto, telefono, whatsapp, email, representante_legal, nit, naturaleza_juridica, delegado, tiempo_constitucion, rut_camara_comercio, responsable_cdmb, novedad, tipo_negocio_verde, codigo_marca, anio_registro, cota_msnm, este, norte, aplicacion_ficha_2025, observaciones, registro_nacional_turismo, uso_suelo, concesion_aguas, concesion_aguas_vencimiento, vertimientos, vertimientos_vencimiento, pueaa, pgris, pozo_septico, alcantarillado, ica, ica_vencimiento, invima, invima_vencimiento, certificado_tenencia_animales, buenas_practicas_agricolas, buenas_practicas_apicolas, registro_apicola, intervencion_cauce, capacidad_carga, sstt, canal_venta, exportacion, huella_carbono, fortalecimiento_tecnico, fortalecimiento_academico, fortalecimiento_financiero, internacionalizacion, certificaciones, posicionamiento_marca, beneficios_ventanilla, fortalezas_ambiental, fortalezas_social, fortalezas_economico, debilidades_ambiental, debilidades_social, debilidades_financiera, emprendimiento_verde, sello_marca, avalado, destacado, activo) values ('3b04df32-8c68-4354-ba23-0415461363ce', 'NUTRATECH', generar_slug_unico('NUTRATECH', '3b04df32-8c68-4354-ba23-0415461363ce'), (select id from categorias_oficiales where slug = 'bioproductos-servicios-sostenibles'), 'Bucaramanga', (select id from veredas where municipio = 'Bucaramanga' and slug = 'perimetro-urbano'), 'CARRERA 8 # 20N-148 PARQUE INDUSTRIAL RUTA 169 Bodega 13', null, null, 'NutraTech S.A.S. es una empresa dedicada al desarrollo y comercialización de aditivos naturales para la alimentación animal, especialmente enfocados en…', 'NutraTech S.A.S. es una empresa dedicada al desarrollo y comercialización de aditivos naturales para la alimentación animal, especialmente enfocados en mejorar la pigmentación de la piel del pollo y la yema del huevo. Su producción se basa en la formulación de núcleos biotecnológicos con compuestos naturales como achiote, cascarilla de café y harina de guayaba. Está dirigida al sector avícola y productores de alimento animal, comercializando sus productos de manera directa a empresas y productores del sector pecuario.', 'PIGMENTANTE PARA LA PIEL DE POLLO Y YEMA DE HUEVO', '3167840327', '573167840327', 'gerencia@nutratech.com.co', 'HELY ARGUELLO AMADO', '901137564-1', 'Jurídica', null, null, 'Camara de comercio', 'SUJEY DÍAZ', 'ACTIVO', null, null, 2026, null, null, null, null, null, null, 'NO', 'ACUEDUCTO', null, null, null, 'NO', 'SI', null, 'SI', 'Jurídica', null, null, null, null, 'NO', null, null, null, null, 'NO', 'B2B', 'NO', 'NO', null, null, null, 'NO', null, null, null, null, null, null, null, null, null, true, false, false, false, true);
insert into negocios_categorias (negocio_id, categoria_oficial_id) values ('3b04df32-8c68-4354-ba23-0415461363ce', (select id from categorias_oficiales where slug = 'bioproductos-servicios-sostenibles'));
insert into negocios_subcategorias (negocio_id, subcategoria_id) select '3b04df32-8c68-4354-ba23-0415461363ce', id from subcategorias where slug = 'biotecnologia';
insert into negocios_actividades (negocio_id, actividad_productiva_id) select '3b04df32-8c68-4354-ba23-0415461363ce', id from actividades_productivas where slug = 'productos-biotecnologia';

-- CROPIABONO
insert into negocios (id, nombre, slug, categoria_oficial_id, municipio, vereda_id, direccion, latitud, longitud, descripcion_corta, descripcion, producto, telefono, whatsapp, email, representante_legal, nit, naturaleza_juridica, delegado, tiempo_constitucion, rut_camara_comercio, responsable_cdmb, novedad, tipo_negocio_verde, codigo_marca, anio_registro, cota_msnm, este, norte, aplicacion_ficha_2025, observaciones, registro_nacional_turismo, uso_suelo, concesion_aguas, concesion_aguas_vencimiento, vertimientos, vertimientos_vencimiento, pueaa, pgris, pozo_septico, alcantarillado, ica, ica_vencimiento, invima, invima_vencimiento, certificado_tenencia_animales, buenas_practicas_agricolas, buenas_practicas_apicolas, registro_apicola, intervencion_cauce, capacidad_carga, sstt, canal_venta, exportacion, huella_carbono, fortalecimiento_tecnico, fortalecimiento_academico, fortalecimiento_financiero, internacionalizacion, certificaciones, posicionamiento_marca, beneficios_ventanilla, fortalezas_ambiental, fortalezas_social, fortalezas_economico, debilidades_ambiental, debilidades_social, debilidades_financiera, emprendimiento_verde, sello_marca, avalado, destacado, activo) values ('85ed3209-a953-4468-95ba-6e7fdda1f5c9', 'CROPIABONO', generar_slug_unico('CROPIABONO', '85ed3209-a953-4468-95ba-6e7fdda1f5c9'), (select id from categorias_oficiales where slug = 'bioproductos-servicios-sostenibles'), 'Piedecuesta', (select id from veredas where municipio = 'Piedecuesta' and slug = 'mesita-de-san-javier'), 'VEREDA MESITA DE SAN JAVIER FINCA TACAMA', null, null, 'Fabricación de abonos y compuestos inorgánicos nitrogenados ( materia prima: gallinaza, caprinaza, polialiyta y roca fosforica)', 'Fabricación de abonos y compuestos inorgánicos nitrogenados ( materia prima: gallinaza, caprinaza, polialiyta y roca fosforica)', 'ABONO ORGÁNICO MINERAL', '3208957298', '573208957298', 'cropiabono@gmail.com', 'JAVIER EDUARDO MANTILLA BUITAGRO', '1102374899-1', 'Natural', null, '35 MESES', 'Camara de comercio', 'ANDRES VALDERRAMA', 'ACTIVO', null, null, 2026, null, null, null, null, null, null, 'NO', 'NO', null, 'NO', null, 'NO', 'SI', 'SI', null, 'Natural', null, null, null, null, null, null, null, null, null, 'NO', 'B2C', 'NO', 'NO', null, null, null, 'NO', null, null, null, null, null, null, null, null, null, true, false, false, false, true);
insert into negocios_categorias (negocio_id, categoria_oficial_id) values ('85ed3209-a953-4468-95ba-6e7fdda1f5c9', (select id from categorias_oficiales where slug = 'bioproductos-servicios-sostenibles'));
insert into negocios_subcategorias (negocio_id, subcategoria_id) select '85ed3209-a953-4468-95ba-6e7fdda1f5c9', id from subcategorias where slug = 'agrosistemas-sostenibles';
insert into negocios_actividades (negocio_id, actividad_productiva_id) select '85ed3209-a953-4468-95ba-6e7fdda1f5c9', id from actividades_productivas where slug = 'agricultura-organica';

-- DANYAN
insert into negocios (id, nombre, slug, categoria_oficial_id, municipio, vereda_id, direccion, latitud, longitud, descripcion_corta, descripcion, producto, telefono, whatsapp, email, representante_legal, nit, naturaleza_juridica, delegado, tiempo_constitucion, rut_camara_comercio, responsable_cdmb, novedad, tipo_negocio_verde, codigo_marca, anio_registro, cota_msnm, este, norte, aplicacion_ficha_2025, observaciones, registro_nacional_turismo, uso_suelo, concesion_aguas, concesion_aguas_vencimiento, vertimientos, vertimientos_vencimiento, pueaa, pgris, pozo_septico, alcantarillado, ica, ica_vencimiento, invima, invima_vencimiento, certificado_tenencia_animales, buenas_practicas_agricolas, buenas_practicas_apicolas, registro_apicola, intervencion_cauce, capacidad_carga, sstt, canal_venta, exportacion, huella_carbono, fortalecimiento_tecnico, fortalecimiento_academico, fortalecimiento_financiero, internacionalizacion, certificaciones, posicionamiento_marca, beneficios_ventanilla, fortalezas_ambiental, fortalezas_social, fortalezas_economico, debilidades_ambiental, debilidades_social, debilidades_financiera, emprendimiento_verde, sello_marca, avalado, destacado, activo) values ('3c58b48e-168b-4032-90a5-366e939867d9', 'DANYAN', generar_slug_unico('DANYAN', '3c58b48e-168b-4032-90a5-366e939867d9'), (select id from categorias_oficiales where slug = 'bioproductos-servicios-sostenibles'), 'Bucaramanga', (select id from veredas where municipio = 'Bucaramanga' and slug = 'perimetro-urbano'), 'CRA 8W NO. 61 - 18 MUTIS CONJUNTO FUNDADORES 2', null, null, 'La empresa se dedica a la fabricación y comercialización de desodorantes artesanales y talcos exfoliantes naturales, elaborados a base de componentes…', 'La empresa se dedica a la fabricación y comercialización de desodorantes artesanales y talcos exfoliantes naturales, elaborados a base de componentes naturales, con propiedades aclarantes, ofreciendo productos asequibles y amigables con el cuidado personal y el medio ambiente.', 'DESODORANTES Y TALCOS', '3183163685 - 3208944061', '3183163685 - 3208944061', 'danyan.sostenible@gmail.com', 'DANIEL SANTIAGO LINARES TEJEDOR', '1098612330-1', 'Natural', 'LYAN PIERRE FELIPE GALVIS GIL', '12 MESES', 'Camara de comercio', 'SUJEY DÍAZ', 'ACTIVO', null, null, 2026, null, null, null, null, null, null, null, 'ACUEDUCTO', null, null, null, 'NO', 'NO', null, 'SI', 'Natural', null, 'NO', null, null, null, null, null, null, null, 'NO', 'B2C', 'NO', 'NO', null, null, null, 'NO', null, null, null, null, null, null, null, null, null, true, false, false, false, true);
insert into negocios_categorias (negocio_id, categoria_oficial_id) values ('3c58b48e-168b-4032-90a5-366e939867d9', (select id from categorias_oficiales where slug = 'bioproductos-servicios-sostenibles'));
insert into negocios_subcategorias (negocio_id, subcategoria_id) select '3c58b48e-168b-4032-90a5-366e939867d9', id from subcategorias where slug = 'agroindustria-sostenible';
insert into negocios_actividades (negocio_id, actividad_productiva_id) select '3c58b48e-168b-4032-90a5-366e939867d9', id from actividades_productivas where slug = 'agroindustrial-no-alimentario';

-- MIEL AMELITA
insert into negocios (id, nombre, slug, categoria_oficial_id, municipio, vereda_id, direccion, latitud, longitud, descripcion_corta, descripcion, producto, telefono, whatsapp, email, representante_legal, nit, naturaleza_juridica, delegado, tiempo_constitucion, rut_camara_comercio, responsable_cdmb, novedad, tipo_negocio_verde, codigo_marca, anio_registro, cota_msnm, este, norte, aplicacion_ficha_2025, observaciones, registro_nacional_turismo, uso_suelo, concesion_aguas, concesion_aguas_vencimiento, vertimientos, vertimientos_vencimiento, pueaa, pgris, pozo_septico, alcantarillado, ica, ica_vencimiento, invima, invima_vencimiento, certificado_tenencia_animales, buenas_practicas_agricolas, buenas_practicas_apicolas, registro_apicola, intervencion_cauce, capacidad_carga, sstt, canal_venta, exportacion, huella_carbono, fortalecimiento_tecnico, fortalecimiento_academico, fortalecimiento_financiero, internacionalizacion, certificaciones, posicionamiento_marca, beneficios_ventanilla, fortalezas_ambiental, fortalezas_social, fortalezas_economico, debilidades_ambiental, debilidades_social, debilidades_financiera, emprendimiento_verde, sello_marca, avalado, destacado, activo) values ('d7bbf1b1-33e9-4974-afd4-a460c8ff0ff7', 'MIEL AMELITA', generar_slug_unico('MIEL AMELITA', 'd7bbf1b1-33e9-4974-afd4-a460c8ff0ff7'), (select id from categorias_oficiales where slug = 'bioproductos-servicios-sostenibles'), 'Suratá', (select id from veredas where municipio = 'Suratá' and slug = 'el-porvenir'), 'VEREDA EL PORVENIR, FINCA VILLANUEVA SURATA', null, null, 'Producción de miel, hidromiel, balsamo de labios sin conservantes ni quimicos', 'Producción de miel, hidromiel, balsamo de labios sin conservantes ni quimicos', 'HIDROMIEL', '3154023352', '573154023352', 'yanethmendozav@yahoo.es', 'SANTOS YANETH MENDOZA VILLABONA', '63318649', null, null, null, 'Rut', 'LUZ ANDREA ISAZA', 'ACTIVO', null, null, 2026, null, null, null, null, null, null, 'NO', 'NO', null, null, null, 'NO', 'NO', 'SI', null, null, null, 'NO', null, null, null, 'NO', 'NO', null, null, 'NO', 'B2C', 'NO', 'NO', null, null, null, 'NO', null, null, null, null, null, null, null, null, null, true, false, false, false, true);
insert into negocios_categorias (negocio_id, categoria_oficial_id) values ('d7bbf1b1-33e9-4974-afd4-a460c8ff0ff7', (select id from categorias_oficiales where slug = 'bioproductos-servicios-sostenibles'));
insert into negocios_subcategorias (negocio_id, subcategoria_id) select 'd7bbf1b1-33e9-4974-afd4-a460c8ff0ff7', id from subcategorias where slug = 'agroindustria-sostenible';
insert into negocios_actividades (negocio_id, actividad_productiva_id) select 'd7bbf1b1-33e9-4974-afd4-a460c8ff0ff7', id from actividades_productivas where slug = 'agroindustrial-alimentario';

-- WAYPA
insert into negocios (id, nombre, slug, categoria_oficial_id, municipio, vereda_id, direccion, latitud, longitud, descripcion_corta, descripcion, producto, telefono, whatsapp, email, representante_legal, nit, naturaleza_juridica, delegado, tiempo_constitucion, rut_camara_comercio, responsable_cdmb, novedad, tipo_negocio_verde, codigo_marca, anio_registro, cota_msnm, este, norte, aplicacion_ficha_2025, observaciones, registro_nacional_turismo, uso_suelo, concesion_aguas, concesion_aguas_vencimiento, vertimientos, vertimientos_vencimiento, pueaa, pgris, pozo_septico, alcantarillado, ica, ica_vencimiento, invima, invima_vencimiento, certificado_tenencia_animales, buenas_practicas_agricolas, buenas_practicas_apicolas, registro_apicola, intervencion_cauce, capacidad_carga, sstt, canal_venta, exportacion, huella_carbono, fortalecimiento_tecnico, fortalecimiento_academico, fortalecimiento_financiero, internacionalizacion, certificaciones, posicionamiento_marca, beneficios_ventanilla, fortalezas_ambiental, fortalezas_social, fortalezas_economico, debilidades_ambiental, debilidades_social, debilidades_financiera, emprendimiento_verde, sello_marca, avalado, destacado, activo) values ('e54291dd-c45e-49e2-b863-9baea1843c9f', 'WAYPA', generar_slug_unico('WAYPA', 'e54291dd-c45e-49e2-b863-9baea1843c9f'), (select id from categorias_oficiales where slug = 'pendiente-clasificar'), 'Bucaramanga', (select id from veredas where municipio = 'Bucaramanga' and slug = 'perimetro-urbano'), 'CRA 25 # 6 - 10', null, null, null, null, 'ZAPATOS ARTESANALES', '3195305438', '573195305438', 'walterjesus94@gmail.com', 'WALTER JESUS RIVERA MORADO', '1102864130', null, null, null, 'Rut', 'SARY YULITZA HIDALGO', 'ACTIVO', null, null, 2026, null, null, null, null, null, null, null, 'ACUEDUCTO', null, null, null, 'NO', 'NO', null, 'SI', null, null, null, null, null, null, null, null, null, null, 'NO', 'B2B', 'NO', 'NO', null, null, null, 'NO', null, null, null, null, null, null, null, null, null, true, false, false, false, true);
insert into negocios_categorias (negocio_id, categoria_oficial_id) values ('e54291dd-c45e-49e2-b863-9baea1843c9f', (select id from categorias_oficiales where slug = 'pendiente-clasificar'));

-- MIRADOR DEL SHADDAI
insert into negocios (id, nombre, slug, categoria_oficial_id, municipio, vereda_id, direccion, latitud, longitud, descripcion_corta, descripcion, producto, telefono, whatsapp, email, representante_legal, nit, naturaleza_juridica, delegado, tiempo_constitucion, rut_camara_comercio, responsable_cdmb, novedad, tipo_negocio_verde, codigo_marca, anio_registro, cota_msnm, este, norte, aplicacion_ficha_2025, observaciones, registro_nacional_turismo, uso_suelo, concesion_aguas, concesion_aguas_vencimiento, vertimientos, vertimientos_vencimiento, pueaa, pgris, pozo_septico, alcantarillado, ica, ica_vencimiento, invima, invima_vencimiento, certificado_tenencia_animales, buenas_practicas_agricolas, buenas_practicas_apicolas, registro_apicola, intervencion_cauce, capacidad_carga, sstt, canal_venta, exportacion, huella_carbono, fortalecimiento_tecnico, fortalecimiento_academico, fortalecimiento_financiero, internacionalizacion, certificaciones, posicionamiento_marca, beneficios_ventanilla, fortalezas_ambiental, fortalezas_social, fortalezas_economico, debilidades_ambiental, debilidades_social, debilidades_financiera, emprendimiento_verde, sello_marca, avalado, destacado, activo) values ('45b72a71-50d5-4ebf-8709-7f775947e02f', 'MIRADOR DEL SHADDAI', generar_slug_unico('MIRADOR DEL SHADDAI', '45b72a71-50d5-4ebf-8709-7f775947e02f'), (select id from categorias_oficiales where slug = 'pendiente-clasificar'), 'Matanza', (select id from veredas where municipio = 'Matanza' and slug = 'santa-ana'), 'CORREGIMIENTO SANTA CRUZ DE LA COLINA', null, null, null, null, 'CAFÉ ORGÁNICO', '3003256712', '573003256712', 'yanipar@hotmail.com', 'YANETH IBAÑEZ', null, null, null, null, null, 'IAN CARLOS RUIZ', 'ACTIVO', null, null, 2026, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, true, false, false, false, true);
insert into negocios_categorias (negocio_id, categoria_oficial_id) values ('45b72a71-50d5-4ebf-8709-7f775947e02f', (select id from categorias_oficiales where slug = 'pendiente-clasificar'));

-- M963
insert into negocios (id, nombre, slug, categoria_oficial_id, municipio, vereda_id, direccion, latitud, longitud, descripcion_corta, descripcion, producto, telefono, whatsapp, email, representante_legal, nit, naturaleza_juridica, delegado, tiempo_constitucion, rut_camara_comercio, responsable_cdmb, novedad, tipo_negocio_verde, codigo_marca, anio_registro, cota_msnm, este, norte, aplicacion_ficha_2025, observaciones, registro_nacional_turismo, uso_suelo, concesion_aguas, concesion_aguas_vencimiento, vertimientos, vertimientos_vencimiento, pueaa, pgris, pozo_septico, alcantarillado, ica, ica_vencimiento, invima, invima_vencimiento, certificado_tenencia_animales, buenas_practicas_agricolas, buenas_practicas_apicolas, registro_apicola, intervencion_cauce, capacidad_carga, sstt, canal_venta, exportacion, huella_carbono, fortalecimiento_tecnico, fortalecimiento_academico, fortalecimiento_financiero, internacionalizacion, certificaciones, posicionamiento_marca, beneficios_ventanilla, fortalezas_ambiental, fortalezas_social, fortalezas_economico, debilidades_ambiental, debilidades_social, debilidades_financiera, emprendimiento_verde, sello_marca, avalado, destacado, activo) values ('d8bead22-5dc9-464d-b67c-3f0d14224001', 'M963', generar_slug_unico('M963', 'd8bead22-5dc9-464d-b67c-3f0d14224001'), (select id from categorias_oficiales where slug = 'ecoproductos-industriales'), 'Lebrija', (select id from veredas where municipio = 'Lebrija' and slug = 'santa-rosa'), 'CONDOMINIO JJ 3 KM DESPUÉS DEL AEROPUERTO', null, null, 'Productos de joyeria en plata y materiales de origen reciclado tales como cuero, bambu, vinculandose a la economia circular y moda sostenibles', 'Productos de joyeria en plata y materiales de origen reciclado tales como cuero, bambu, vinculandose a la economia circular y moda sostenibles', 'ACCESORIOS DE JOYERIA EN PLATA', '3167272103', '573167272103', 'barragan.marco.2022@gmail.com', 'MARCO BARRAGAN GÓMEZ', '91492323', null, null, null, null, 'VIVIANA ANDREA BARAJAS', 'ACTIVO', null, null, 2026, null, null, null, null, null, null, 'NO', 'ACUEDUCTO VEREDAL', null, null, null, 'NO', 'NO', 'SI', null, null, null, null, null, null, null, null, null, null, null, 'NO', 'B2C', 'NO', 'NO', null, null, null, 'NO', null, null, null, null, null, null, null, null, null, true, false, false, false, true);
insert into negocios_categorias (negocio_id, categoria_oficial_id) values ('d8bead22-5dc9-464d-b67c-3f0d14224001', (select id from categorias_oficiales where slug = 'ecoproductos-industriales'));
insert into negocios_subcategorias (negocio_id, subcategoria_id) select 'd8bead22-5dc9-464d-b67c-3f0d14224001', id from subcategorias where slug = 'moda-sostenible';

-- CAFÉ LA GUACHARACA
insert into negocios (id, nombre, slug, categoria_oficial_id, municipio, vereda_id, direccion, latitud, longitud, descripcion_corta, descripcion, producto, telefono, whatsapp, email, representante_legal, nit, naturaleza_juridica, delegado, tiempo_constitucion, rut_camara_comercio, responsable_cdmb, novedad, tipo_negocio_verde, codigo_marca, anio_registro, cota_msnm, este, norte, aplicacion_ficha_2025, observaciones, registro_nacional_turismo, uso_suelo, concesion_aguas, concesion_aguas_vencimiento, vertimientos, vertimientos_vencimiento, pueaa, pgris, pozo_septico, alcantarillado, ica, ica_vencimiento, invima, invima_vencimiento, certificado_tenencia_animales, buenas_practicas_agricolas, buenas_practicas_apicolas, registro_apicola, intervencion_cauce, capacidad_carga, sstt, canal_venta, exportacion, huella_carbono, fortalecimiento_tecnico, fortalecimiento_academico, fortalecimiento_financiero, internacionalizacion, certificaciones, posicionamiento_marca, beneficios_ventanilla, fortalezas_ambiental, fortalezas_social, fortalezas_economico, debilidades_ambiental, debilidades_social, debilidades_financiera, emprendimiento_verde, sello_marca, avalado, destacado, activo) values ('7bb811a3-2fcb-4b13-8182-3d68928ed116', 'CAFÉ LA GUACHARACA', generar_slug_unico('CAFÉ LA GUACHARACA', '7bb811a3-2fcb-4b13-8182-3d68928ed116'), (select id from categorias_oficiales where slug = 'bioproductos-servicios-sostenibles'), 'Piedecuesta', (select id from veredas where municipio = 'Piedecuesta' and slug = 'via-curos'), 'FINCA SAN FELIPE DEL OCASO, VEREDA VIA CUROS, MESA DE LOS SANTOS KM7', null, null, 'Cultivo de café, comercialización de café empacado o en grano', 'Cultivo de café, comercialización de café empacado o en grano', 'CAFÉ', '3138026724', '573138026724', 'au.bau91@gmail.com', 'AURA LILIANA BAUTISTA VALBUENA', '1098703297-5', 'Natural', null, '21 MESES', 'Camara de comercio', 'LAURA CAROLINA RODRIGUEZ', 'ACTIVO', null, null, 2026, null, null, null, null, null, null, 'NO', 'NO', null, null, null, 'SI', 'NO', 'SI', null, 'Natural', null, 'SI', null, null, 'NO', null, null, null, null, 'NO', 'B2C', 'NO', 'SI', null, null, null, 'NO', null, null, null, null, null, null, null, null, null, true, false, false, false, true);
insert into negocios_categorias (negocio_id, categoria_oficial_id) values ('7bb811a3-2fcb-4b13-8182-3d68928ed116', (select id from categorias_oficiales where slug = 'bioproductos-servicios-sostenibles'));
insert into negocios_subcategorias (negocio_id, subcategoria_id) select '7bb811a3-2fcb-4b13-8182-3d68928ed116', id from subcategorias where slug = 'agroindustria-sostenible';
insert into negocios_actividades (negocio_id, actividad_productiva_id) select '7bb811a3-2fcb-4b13-8182-3d68928ed116', id from actividades_productivas where slug = 'agroindustrial-alimentario';

-- SAJUPLATS S.A.S
insert into negocios (id, nombre, slug, categoria_oficial_id, municipio, vereda_id, direccion, latitud, longitud, descripcion_corta, descripcion, producto, telefono, whatsapp, email, representante_legal, nit, naturaleza_juridica, delegado, tiempo_constitucion, rut_camara_comercio, responsable_cdmb, novedad, tipo_negocio_verde, codigo_marca, anio_registro, cota_msnm, este, norte, aplicacion_ficha_2025, observaciones, registro_nacional_turismo, uso_suelo, concesion_aguas, concesion_aguas_vencimiento, vertimientos, vertimientos_vencimiento, pueaa, pgris, pozo_septico, alcantarillado, ica, ica_vencimiento, invima, invima_vencimiento, certificado_tenencia_animales, buenas_practicas_agricolas, buenas_practicas_apicolas, registro_apicola, intervencion_cauce, capacidad_carga, sstt, canal_venta, exportacion, huella_carbono, fortalecimiento_tecnico, fortalecimiento_academico, fortalecimiento_financiero, internacionalizacion, certificaciones, posicionamiento_marca, beneficios_ventanilla, fortalezas_ambiental, fortalezas_social, fortalezas_economico, debilidades_ambiental, debilidades_social, debilidades_financiera, emprendimiento_verde, sello_marca, avalado, destacado, activo) values ('d91febee-3201-4c3f-afee-0d5c4903fe19', 'SAJUPLATS S.A.S', generar_slug_unico('SAJUPLATS S.A.S', 'd91febee-3201-4c3f-afee-0d5c4903fe19'), (select id from categorias_oficiales where slug = 'ecoproductos-industriales'), 'Girón', (select id from veredas where municipio = 'Girón' and slug = 'perimetro-urbano'), 'CRA 0 #3 - 36 LOTE A CHIMITA', null, null, 'Es una empresa sas que se dedica a la recuperacion, transformacion y comercializacion de materias primas plasticas flexibles, mediante un proceso productivo…', 'Es una empresa sas que se dedica a la recuperacion, transformacion y comercializacion de materias primas plasticas flexibles, mediante un proceso productivo (clasificacion y aglutinada) para venderle a empresas que fabrican articulos plasticos (inyeccion y extrusion) con materia prima reciclada el cual se comercializa por venta directa al por mayor', 'RECUPERACIÓN DE MATERIA PRIMA PLASTICA FLEXIBLE', '3228345953', '573228345953', 'sajuplast@gmail.com', 'JUAN JOSÉ OROZCO NAVARRETE', '901948834-3', 'Jurídica', null, '19 MESES', 'Camara de comercio', 'SIOMAR FLOREZ', 'ACTIVO', null, null, 2026, null, null, null, null, null, null, 'NO', 'ACUEDUCTO', null, null, null, 'NO', 'NO', null, 'SI', 'Juridica', null, null, null, null, null, null, null, null, null, 'NO', 'B2B', 'NO', 'NO', null, null, null, 'NO', null, null, null, null, null, null, null, null, null, true, false, false, false, true);
insert into negocios_categorias (negocio_id, categoria_oficial_id) values ('d91febee-3201-4c3f-afee-0d5c4903fe19', (select id from categorias_oficiales where slug = 'ecoproductos-industriales'));
insert into negocios_actividades (negocio_id, actividad_productiva_id) select 'd91febee-3201-4c3f-afee-0d5c4903fe19', id from actividades_productivas where slug = 'aprovechamiento-residuos-inorganicos';

-- PASIÓN DE HOGAR
insert into negocios (id, nombre, slug, categoria_oficial_id, municipio, vereda_id, direccion, latitud, longitud, descripcion_corta, descripcion, producto, telefono, whatsapp, email, representante_legal, nit, naturaleza_juridica, delegado, tiempo_constitucion, rut_camara_comercio, responsable_cdmb, novedad, tipo_negocio_verde, codigo_marca, anio_registro, cota_msnm, este, norte, aplicacion_ficha_2025, observaciones, registro_nacional_turismo, uso_suelo, concesion_aguas, concesion_aguas_vencimiento, vertimientos, vertimientos_vencimiento, pueaa, pgris, pozo_septico, alcantarillado, ica, ica_vencimiento, invima, invima_vencimiento, certificado_tenencia_animales, buenas_practicas_agricolas, buenas_practicas_apicolas, registro_apicola, intervencion_cauce, capacidad_carga, sstt, canal_venta, exportacion, huella_carbono, fortalecimiento_tecnico, fortalecimiento_academico, fortalecimiento_financiero, internacionalizacion, certificaciones, posicionamiento_marca, beneficios_ventanilla, fortalezas_ambiental, fortalezas_social, fortalezas_economico, debilidades_ambiental, debilidades_social, debilidades_financiera, emprendimiento_verde, sello_marca, avalado, destacado, activo) values ('de6ded8c-d4d6-47e8-a583-d19df88c613d', 'PASIÓN DE HOGAR', generar_slug_unico('PASIÓN DE HOGAR', 'de6ded8c-d4d6-47e8-a583-d19df88c613d'), (select id from categorias_oficiales where slug = 'bioproductos-servicios-sostenibles'), 'Rionegro', (select id from veredas where municipio = 'Rionegro' and slug = 'valparaiso'), 'VEREDA VALPARAISO, FINCA EL JAZMÍN', null, null, 'Agricultora, transformadora y comercializadora de productos de cacao, dentro de los caules se encuentra artesanias de cacao…, artesanal no hay equipos…,…', 'Agricultora, transformadora y comercializadora de productos de cacao, dentro de los caules se encuentra artesanias de cacao…, artesanal no hay equipos…, familias dado que venden productos naturales de cacao, turrones, etc., y artesania. Vende en ferias y con apoyo de Fedecacao, y bajo pedidos dado los productos publicados en las redes sociales de Facebook e Instagram...', 'VENTA DE CACAO Y CHUCULA', '3184958022', '573184958022', 'pasiondehogar@gmail.com - sunialexis76@gmail.com', 'SUNY SANTAMARIA GALEANO', '63252922-6', 'Natural', null, '31 MESES', 'Camara de comercio', 'YEINNI PAOLA CRISTANCHO', 'ACTIVO', null, null, 2026, null, null, null, null, null, null, 'NO', 'SI', '2032-09-18', 'SI', null, 'NO', 'NO', 'SI', null, 'Natural', null, 'NO', null, null, 'NO', null, null, null, null, 'NO', 'B2C', 'NO', 'NO', null, null, null, 'NO', null, null, null, null, null, null, null, null, null, true, false, false, false, true);
insert into negocios_categorias (negocio_id, categoria_oficial_id) values ('de6ded8c-d4d6-47e8-a583-d19df88c613d', (select id from categorias_oficiales where slug = 'bioproductos-servicios-sostenibles'));
insert into negocios_subcategorias (negocio_id, subcategoria_id) select 'de6ded8c-d4d6-47e8-a583-d19df88c613d', id from subcategorias where slug = 'agrosistemas-sostenibles';
insert into negocios_actividades (negocio_id, actividad_productiva_id) select 'de6ded8c-d4d6-47e8-a583-d19df88c613d', id from actividades_productivas where slug = 'agroindustrial-alimentario';

-- ABRIGO DE FLORA
insert into negocios (id, nombre, slug, categoria_oficial_id, municipio, vereda_id, direccion, latitud, longitud, descripcion_corta, descripcion, producto, telefono, whatsapp, email, representante_legal, nit, naturaleza_juridica, delegado, tiempo_constitucion, rut_camara_comercio, responsable_cdmb, novedad, tipo_negocio_verde, codigo_marca, anio_registro, cota_msnm, este, norte, aplicacion_ficha_2025, observaciones, registro_nacional_turismo, uso_suelo, concesion_aguas, concesion_aguas_vencimiento, vertimientos, vertimientos_vencimiento, pueaa, pgris, pozo_septico, alcantarillado, ica, ica_vencimiento, invima, invima_vencimiento, certificado_tenencia_animales, buenas_practicas_agricolas, buenas_practicas_apicolas, registro_apicola, intervencion_cauce, capacidad_carga, sstt, canal_venta, exportacion, huella_carbono, fortalecimiento_tecnico, fortalecimiento_academico, fortalecimiento_financiero, internacionalizacion, certificaciones, posicionamiento_marca, beneficios_ventanilla, fortalezas_ambiental, fortalezas_social, fortalezas_economico, debilidades_ambiental, debilidades_social, debilidades_financiera, emprendimiento_verde, sello_marca, avalado, destacado, activo) values ('a198c39d-3760-474c-b8b0-23979efb35d6', 'ABRIGO DE FLORA', generar_slug_unico('ABRIGO DE FLORA', 'a198c39d-3760-474c-b8b0-23979efb35d6'), (select id from categorias_oficiales where slug = 'pendiente-clasificar'), 'Piedecuesta', (select id from veredas where municipio = 'Piedecuesta' and slug = 'sevilla'), 'VEREDA SEVILLA FINCA MADRIGAL SECTOR EL MANZANO', null, null, null, null, 'COSMÉTICA BOTÁNICA NATURAL', '3174876930', '573174876930', 'abrigodeflorase@gmail.com', 'ERIKA FERNANDA DURAN GOMEZ', '37619813', null, null, null, 'Rut', 'GENNY JULIANA FERREIRA', 'ACTIVO', null, null, 2026, null, null, null, null, null, null, 'NO', 'ACUEDUCTO VEREDAL', null, null, null, 'NO', 'NO', null, null, null, null, 'NO', null, null, null, null, null, null, null, 'NO', 'B2C', 'NO', 'NO', null, null, null, 'NO', null, null, null, null, null, null, null, null, null, true, false, false, false, true);
insert into negocios_categorias (negocio_id, categoria_oficial_id) values ('a198c39d-3760-474c-b8b0-23979efb35d6', (select id from categorias_oficiales where slug = 'pendiente-clasificar'));


commit;
